### ISSUE TITLE
problem: apk compilation error

### ISSUE THREAD

**Issue by old4error** [revanced/revanced-cli#102]
## 🐞 Issue

getting an error while building revanced apk after merging patches
## ⚙ Reproduce

command:
java -jar revanced-cli-*-all.jar --experimental -a base.apk -d $(adb devices | grep -o '\b[a-f0-9]\+\b') -c -o youtube-revanced.apk -b revanced-patches-*.jar -m app-release-unsigned-*.apk -e amoled -e premium-heading -e hide-shorts-button -e disable-fullscreen-panels -e hide-cast-button -e microg-support -e seekbar-tapping -e hide-infocard-suggestions -e enable-debugging -e swipe-controls -e autorepeat-by-default -e enable-wide-searchbar -e force-vp9-codec --mount
## ⚠ Additional context

Log:

INFO: Compiling resources 
WARNING: /home/old4ever/revanced-build/revanced-cache/res/layout/skip_sponsor_button.xml:5: error: resource drawable/quantum_ic_skip_next_white_24 (aka com.google.android.youtube:drawable/quantum_ic_skip_next_white_24) not found. 
WARNING: error: failed linking file resources. 
**brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_19722525545051879418483325998717487996.tmp, link, -o, /home/old4ever/revanced-build/revanced-cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530387904, --version-name, 17.27.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL2757033453148157283.tmp, -0, arsc, -I, /home/old4ever/.local/share/apktool/framework/1.apk, --manifest, /home/old4ever/revanced-build/revanced-cache/AndroidManifest.xml, /home/old4ever/revanced-build/revanced-cache/build/resources.zip]**
        _at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:199)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)_
**Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_19722525545051879418483325998717487996.tmp, link, -o, /home/old4ever/revanced-build/revanced-cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530387904, --version-name, 17.27.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL2757033453148157283.tmp, -0, arsc, -I, /home/old4ever/.local/share/apktool/framework/1.apk, --manifest, /home/old4ever/revanced-build/revanced-cache/AndroidManifest.xml, /home/old4ever/revanced-build/revanced-cache/build/resources.zip]**
        _at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more_

**Comment by old4error** [comment]
EDIT: excluding sponsorblock patch solves the issue
