### ISSUE TITLE
Broken apk signer

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-cli#11]
The cli's APK signer breaks when signing a resource patched APK file.

**Comment by SVR666** [comment]
`org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1174)
        at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:51)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:84)
        at app.revanced.cli.Patcher$Companion.start$revanced_cli(Patcher.kt:50)
        at app.revanced.cli.MainCommand.run(MainCommand.kt:64)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.MainKt.main(Main.kt:6)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)`

Is this the same error happening with you?

**Comment by oSumAtrIX** [comment]
This is a different error

**Comment by SVR666** [comment]
do you know how to fix it?

**Comment by mhetralla** [comment]
@SVR666 The repo maintainer is unwilling to provide more information about this (this same error happened to other users in the Discord server including me, and they kept replying with vague answers until we figured out what was the problem and how to solve it. Later the project lead [confirmed us](https://discord.com/channels/952946952348270622/953965039105232906/972921492524400670) there was an bad implementation in the project and that trips the security policies in the Oracle's JDK.)  
The solution for the problem you have is using any other Java 17 JDK that is not made by Oracle, for example [Temurin OpenJDK](https://adoptium.net/temurin/releases) or [Azul OpenJDK](https://www.azul.com/downloads/?package=jdk#download-openjdk).

**Comment by oSumAtrIX** [comment]
> The repo maintainer is unwilling to provide more information about this
In my previous comment I have clearly said, you should use the same environment as the workflow is, that includes using the same JDK.

In addition to that this is once again the wrong issue you are replying in. Open a seperate one or/and create a PR.

**Comment by oSumAtrIX** [comment]
Closed with 2975a47d0f682a92da7b3ed455f5078298b0cbaa.
