### ISSUE TITLE
bug: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by sacharbit** [revanced/revanced-cli#115]
### Type

Error while running the CLI

### Bug description

I've got this error while running the CLI : 

```
INFO: Signing youtube-revanced_aligned.apk to youtube-revanced_signed.apk
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
        at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:29)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:58)
        at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:171)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more
```

### Steps to reproduce

Steps to reproduce : 

1. Build from source all of the projects
2. Run this command : 
```java -jar build\libs\revanced-cli-2.9.1-all.jar -b ..\revanced-patches\build\libs\revanced-patches-2.32.1.jar -a "..\com.google.android.youtube_17.29.35-1530650048_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk" -c -e hide-autoplay-button --experimental --mount -o ..\youtube-revanced.apk -m C:\Users\user\Downloads\revanced-integrations\app\build\intermediates\dex\release\mergeDexRelease -d 2aa1f7610d3f7ece```

### Relevant log output

```shell
java -jar build\libs\revanced-cli-2.9.1-all.jar -b ..\revanced-patches\build\libs\revanced-patches-2.32.1.jar -a "..\com.google.android.youtube_17.29.35-1530650048_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk" -c -e hide-autoplay-button --experimental -o ..\youtube-revanced.apk -m C:\Users\user\Downloads\revanced-integrations\app\build\intermediates\dex\release\mergeDexRelease -d 2aa1f7610d3f7ece
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging C:\Users\user\Downloads\revanced-integrations\app\build\intermediates\dex\release\mergeDexRelease
WARNING: Skipping music-video-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping compact-header: Not explicitly included
WARNING: Skipping minimized-playback-music: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping hide-get-premium: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-microg-support: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping general-reddit-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
WARNING: Skipping timeline-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
WARNING: Skipping promo-code-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
INFO: Skipping hide-autoplay-button: Explicitly excluded
INFO: Skipping enable-debugging: Not explicitly included
INFO: general-ads succeeded
INFO: hide-infocard-suggestions succeeded
INFO: video-ads succeeded
INFO: seekbar-tapping succeeded
INFO: swipe-controls succeeded
INFO: amoled succeeded
INFO: premium-heading succeeded
INFO: custom-branding succeeded
INFO: hide-cast-button succeeded
INFO: disable-create-button succeeded
INFO: disable-fullscreen-panels succeeded
INFO: minimized-playback succeeded
INFO: old-quality-layout succeeded
INFO: return-youtube-dislike succeeded
INFO: hide-shorts-button succeeded
INFO: sponsorblock succeeded
INFO: hide-watermark succeeded
INFO: enable-wide-searchbar succeeded
INFO: always-autorepeat succeeded
INFO: custom-playback-speed succeeded
INFO: hdr-auto-brightness succeeded
INFO: microg-support succeeded
INFO: remember-video-quality succeeded
INFO: settings succeeded
INFO: custom-video-buffer succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes8.dex
INFO: Writing resources...
INFO: Aligning youtube-revanced_raw.apk to youtube-revanced_aligned.apk
INFO: Signing youtube-revanced_aligned.apk to youtube-revanced_signed.apk
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
        at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:29)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:58)
        at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:171)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more
```

**Comment by TheJeterLP** [comment]
Use Zulu JDK.

**Comment by sacharbit** [comment]
Oh thanks! That was so simple and written in the doc!
