### ISSUE TITLE
Revanced breaks upon phone restart

### ISSUE THREAD

**Issue by username227** [revanced/revanced-cli#118]
### Type

Error at runtime

### Bug description

I have gotten the CLI to work properly - to install the root variant. It works just fine, but stops working after i restart the phone, after which the app won't start up. I have attached the log output from the logcat of me attempting to open the youtube app (with the revanced logo) after restart, which fails.

### Steps to reproduce

I installed revanced with the following command:
java -jar revanced-cli.jar -a youtube.apk -c -d ZY227SB8F2 -o revanced.apk -b revanced-patches.jar -m integrations.apk -i general-resource-ads -i general-ads -i video-ads -i premium-heading -i integrations -i locale-config-fix -i resource-id-mapping-provider-resource-patch-dependency --mount
then after confirming that it worked, restarted the device. I'm using a Moto G8+

### Relevant log output

```shell
[08-12 13:35:15.267 2170:2594 I/WindowManager]
  SURFACE show Surface(name=Splash Screen com.google.android.youtube)/@0x2fb3420 on display:0: Splash Screen com.google.android.youtube

[08-12 13:35:15.843 19604:19661 E/AndroidRuntime]
FATAL EXCEPTION: cronet-ui-innertube4-2
Process: com.google.android.youtube, PID: 19604
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
	at java.lang.Runtime.load0(Runtime.java:938)
	at java.lang.System.load(System.java:1631)
	at cbn.g(PG:48)
	at qcu.H(PG:7)
	at eiz.a(PG:2)
	at afoa.e(PG:8)
	at afoa.f(PG:5)
	at afoa.c(PG:1)
	at ntf.a(PG:1)
	at nuy.getController(PG:1)
	at abcv.a(PG:2)
	at abcf.c(PG:1)
	at rtx.b(PG:71)
	at cpx.Q(PG:6)
	at unr.t(PG:1)
	at uoo.H(PG:2)
	at uoo.rg(PG:2)
	at stb.a(PG:15)
	at stb.run(PG:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at sjp.run(PG:75)
	at java.lang.Thread.run(Thread.java:919)

[08-12 13:35:15.879 2170:5705 W/ActivityTaskManager]
  Force finishing activity com.google.android.youtube/.app.honeycomb.Shell$HomeActivity

[08-12 13:35:15.963 2170:6658 I/ActivityManager]
Process com.google.android.youtube (pid 19604) has died: vis TOP 

[08-12 13:35:15.964 2170:6658 D/ActivityManager]
makeInactive, ProcessRecord{6968b14 19604:com.google.android.youtube/u0a175}, clear holder.state

[08-12 13:35:15.965 2170:6658 W/ActivityManager]
Scheduling restart of crashed service com.google.android.youtube/androidx.work.impl.background.systemjob.SystemJobService in 1000ms

[08-12 13:35:16.383 2170:2591 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{1983b43 u0 com.google.android.youtube/.app.honeycomb.Shell$HomeActivity t-1 f}
```

**Comment by oSumAtrIX** [comment]
You renamed the jar files and did not include any version information, please update it

**Comment by shrihanDev** [comment]
@oSumAtrIX This is basically #17.

**Comment by tamliad123456** [comment]
happens to me too.

my cli command is:
`java -jar ./revanced-cli-2.12.0-all.jar -a youtube.apk -c -d 1336ab98 -o output.apk -b revanced-patches-2.69.2.jar -e microg-support -m app-release-unsigned.apk --mount`

**Comment by oSumAtrIX** [comment]
Open an issue @tamliad123456.

**Comment by oSumAtrIX** [comment]
Fixed couple months ago.
