### ISSUE TITLE
Error while compiling reddit

### ISSUE THREAD

**Issue by th3g0dfather** [revanced/revanced-cli#119]
### Type

Error at runtime

### Bug description

Error while compiling reddit with command line

### Steps to reproduce

java -jar ..\youtube\revanced-cli-2.9.3-all.jar -a ..\youtube\reddit.apk -c -d f27e4ec6 -o revanced.apk -m ..\youtube\app-release-unsigned.apk -b ..\youtube\revanced-patches-2.39.0.jar --mount

### Relevant log output

```shell
INFO: Deleting existing resource cache directory
WARNING: Skipping package group: com.reddit.frontpage.creatorkit_dynamicfeature
INFO: Decoding resources
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7e0c0000
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7e0e0000
INFO: Reading dex files
INFO: Merging ..\youtube\app-release-unsigned.apk
WARNING: Skipping timeline-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.twitter.android
WARNING: Skipping pflotsh-ecmwf-subscription-unlock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
WARNING: Skipping minimized-playback-music: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping hide-get-premium: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping compact-header: Not explicitly included
WARNING: Skipping upgrade-button-remover: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-microg-support: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-video-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping promo-code-unlock: Incompatible with com.reddit.frontpage. This patch is only compatible with de.dwd.warnapp
WARNING: Skipping tiktok-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping swipe-controls: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping seekbar-tapping: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping minimized-playback: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping amoled: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping disable-create-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-cast-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping return-youtube-dislike: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-autoplay-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping premium-heading: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping custom-branding: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping disable-fullscreen-panels: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping old-quality-layout: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-shorts-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-watermark: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping sponsorblock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping enable-wide-searchbar: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping tablet-mini-player: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping custom-video-buffer: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping always-autorepeat: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping microg-support: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping settings: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
INFO: Skipping enable-debugging: Not explicitly included
WARNING: Skipping custom-playback-speed: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hdr-auto-brightness: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping remember-video-quality: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping video-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping general-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-infocard-suggestions: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
INFO: general-reddit-ads succeeded
INFO: Compiling resources
WARNING: E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\AndroidManifest.xml:524: error: '@2114715648' is incompatible with attribute theme (attr) reference.
WARNING: E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\AndroidManifest.xml:697: error: '@2114846720' is incompatible with attribute resource (attr) reference.
WARNING: error: failed processing manifest.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mohit\AppData\Local\Temp\brut_util_Jar_125622070314535065567176103073759125778.tmp, link, -o, E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 32, --version-code, 556666, --version-name, 2022.31.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\mohit\AppData\Local\Temp\APKTOOL1825022762628077995.tmp, -0, arsc, -I, revanced-cache\1.apk, --manifest, E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\AndroidManifest.xml, E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:204)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mohit\AppData\Local\Temp\brut_util_Jar_125622070314535065567176103073759125778.tmp, link, -o, E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 32, --version-code, 556666, --version-name, 2022.31.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\mohit\AppData\Local\Temp\APKTOOL1825022762628077995.tmp, -0, arsc, -I, revanced-cache\1.apk, --manifest, E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\AndroidManifest.xml, E:\zulu17.36.15-ca-jdk17.0.4-win_i686\bin\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more
```

### Additional context

Android 12

**Comment by oSumAtrIX** [comment]
Where did you get the reddit apk?

**Comment by th3g0dfather** [comment]
> Where did you get the reddit apk?

From apkmirror

**Comment by oSumAtrIX** [comment]
Should be fixed now.
