### ISSUE TITLE
bug: app.revanced.patcher.patch.PatchResultError: hdr-brightness-fingerprint-xxz has not been resolved yet.

### ISSUE THREAD

**Issue by sacharbit** [revanced/revanced-cli#121]
### Type

Error while running the CLI

### Bug description

This happens for a lot of features.

Here's the command I run to get the apk : 
```java -jar .\outputs\revanced-cli.jar -b .\outputs\revanced-patches.jar -a ".\outputs\youtube.apk" -c -e hide-autoplay-button --experimental -o .\youtube-revanced.apk -m .\revanced-integrations\app\build\intermediates\dex\release\mergeDexRelease```

After that, I do have an apk but it crashed as soon as I open it.

### Steps to reproduce

1. Run ```java -jar .\outputs\revanced-cli.jar -b .\outputs\revanced-patches.jar -a ".\outputs\youtube.apk" -c -e hide-autoplay-button --experimental -o .\youtube-revanced.apk -m .\revanced-integrations\app\build\intermediates\dex\release\mergeDexRelease```
2. Get the error 

### Relevant log output

```shell
INFOS: Decoding resources
INFOS: Reading dex files
INFOS: Merging .\revanced-integrations\app\build\intermediates\dex\release\mergeDexRelease
AVERTISSEMENT: Skipping pflotsh-ecmwf-subscription-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
AVERTISSEMENT: Skipping music-video-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFOS: Skipping compact-header: Not explicitly included
AVERTISSEMENT: Skipping minimized-playback-music: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping hide-get-premium: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping music-microg-support: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
AVERTISSEMENT: Skipping general-reddit-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
AVERTISSEMENT: Skipping tiktok-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
AVERTISSEMENT: Skipping timeline-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
AVERTISSEMENT: Skipping promo-code-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
INFOS: Skipping hide-autoplay-button: Explicitly excluded
INFOS: Skipping enable-debugging: Not explicitly included
INFOS: general-ads succeeded
INFOS: hide-infocard-suggestions succeeded
INFOS: video-ads succeeded
INFOS: downloads succeeded
INFOS: seekbar-tapping succeeded
GRAVE: swipe-controls failed:
app.revanced.patcher.patch.PatchResultError: swipe-controls-host-activity-fingerprint has not been resolved yet.
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:308)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:324)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.Exception: swipe-controls-host-activity-fingerprint has not been resolved yet.
        at app.revanced.patcher.fingerprint.method.impl.MethodFingerprint.getResult(MethodFingerprint.kt:37)
        at app.revanced.patches.youtube.interaction.swipecontrols.patch.bytecode.SwipeControlsBytecodePatch.execute(SwipeControlsBytecodePatch.kt:43)
        at app.revanced.patches.youtube.interaction.swipecontrols.patch.bytecode.SwipeControlsBytecodePatch.execute(SwipeControlsBytecodePatch.kt:24)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:303)
        ... 16 more
INFOS: amoled succeeded
INFOS: premium-heading succeeded
INFOS: custom-branding succeeded
INFOS: hide-cast-button succeeded
INFOS: disable-create-button succeeded
INFOS: disable-fullscreen-panels succeeded
INFOS: old-quality-layout succeeded
INFOS: return-youtube-dislike succeeded
GRAVE: hide-shorts-button failed:
app.revanced.patcher.patch.PatchResultError: class org.jf.dexlib2.builder.instruction.BuilderInstruction10t cannot be cast to class org.jf.dexlib2.iface.instruction.OneRegisterInstruction (org.jf.dexlib2.builder.instruction.BuilderInstruction10t and org.jf.dexlib2.iface.instruction.OneRegisterInstruction are in unnamed module of loader 'app')
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:308)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:324)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassCastException: class org.jf.dexlib2.builder.instruction.BuilderInstruction10t cannot be cast to class org.jf.dexlib2.iface.instruction.OneRegisterInstruction (org.jf.dexlib2.builder.instruction.BuilderInstruction10t and org.jf.dexlib2.iface.instruction.OneRegisterInstruction are in unnamed module of loader 'app')
        at app.revanced.patches.youtube.layout.shorts.button.patch.ShortsButtonRemoverPatch.execute(ShortsButtonRemoverPatch.kt:71)
        at app.revanced.patches.youtube.layout.shorts.button.patch.ShortsButtonRemoverPatch.execute(ShortsButtonRemoverPatch.kt:23)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:303)
        ... 16 more
INFOS: sponsorblock succeeded
GRAVE: tablet-mini-player failed:
app.revanced.patcher.patch.PatchResultError: mini-player-dimensions-calculator-fingerprint has not been resolved yet.
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:308)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:324)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.Exception: mini-player-dimensions-calculator-fingerprint has not been resolved yet.
        at app.revanced.patcher.fingerprint.method.impl.MethodFingerprint.getResult(MethodFingerprint.kt:37)
        at app.revanced.patches.youtube.layout.tabletminiplayer.patch.TabletMiniPlayerPatch.execute(TabletMiniPlayerPatch.kt:49)
        at app.revanced.patches.youtube.layout.tabletminiplayer.patch.TabletMiniPlayerPatch.execute(TabletMiniPlayerPatch.kt:27)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:303)
        ... 16 more
INFOS: hide-watermark succeeded
INFOS: enable-wide-searchbar succeeded
INFOS: always-autorepeat succeeded
INFOS: client-spoof succeeded
INFOS: custom-playback-speed succeeded
GRAVE: hdr-auto-brightness failed:
app.revanced.patcher.patch.PatchResultError: hdr-brightness-fingerprint-xxz has not been resolved yet.
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:308)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:324)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.Exception: hdr-brightness-fingerprint-xxz has not been resolved yet.
        at app.revanced.patcher.fingerprint.method.impl.MethodFingerprint.getResult(MethodFingerprint.kt:37)
        at app.revanced.patches.youtube.misc.hdrbrightness.patch.HDRBrightnessPatch.execute(HDRBrightnessPatch.kt:46)
        at app.revanced.patches.youtube.misc.hdrbrightness.patch.HDRBrightnessPatch.execute(HDRBrightnessPatch.kt:24)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:303)
        ... 16 more
INFOS: microg-support succeeded
INFOS: minimized-playback succeeded
INFOS: remember-video-quality succeeded
INFOS: settings succeeded
INFOS: custom-video-buffer succeeded
INFOS: Compiling resources
INFOS: Writing modified dex files
INFOS: Writing dex file classes.dex
INFOS: Writing dex file classes2.dex
INFOS: Writing dex file classes4.dex
INFOS: Writing dex file classes3.dex
INFOS: Writing dex file classes5.dex
INFOS: Writing dex file classes6.dex
INFOS: Writing dex file classes7.dex
INFOS: Writing dex file classes8.dex
INFOS: Writing resources...
INFOS: Aligning youtube-revanced_raw.apk to youtube-revanced_aligned.apk
INFOS: Signing youtube-revanced_aligned.apk to youtube-revanced_signed.apk
INFOS: Found existing keystore: youtube-revanced.keystore
INFOS: Copying youtube-revanced_signed.apk to youtube-revanced.apk
INFOS: Cleaned up cache directory
INFOS: Finished
```

**Comment by Canny1913** [comment]
Please use a supported version.

**Comment by sacharbit** [comment]
yep thanks

I knew it was a dumb question haha

**Comment by TheJeterLP** [comment]
Also the integrations are being used wrong.

**Comment by sacharbit** [comment]
> Also the integrations are being used wrong.

Can you please elaborate on this?

**Comment by TheJeterLP** [comment]
> > Also the integrations are being used wrong.
> 
> Can you please elaborate on this? 

Look into the documentation for what file to use
