### ISSUE TITLE
bug: Revanced-cli crashes while applying pathces to TikTok apk

### ISSUE THREAD

**Issue by mirochu** [revanced/revanced-cli#124]
### Type

Error while running the CLI

### Bug description

Revanced cli crashes while patching TikTok apk, tried with 3 different version of tiktok (26.0.3, 26.0.2, 25.6.2). 
Tried with and without the revanced integrations (https://github.com/revanced/revanced-integrations)

### Steps to reproduce

1: Download zulu jdk (Windows)
2: Download all the necessary files (revanced-cli, revanced-pathces, TikTok apk)
3: Run `java -jar\revanced-cli-2.9.5-all.jar -a tiktok.apk -b revanced-patches-2.50.4.jar -c  -o tiktokpathced.apk `

### Relevant log output

```shell
INFORMAZIONI: Deleting existing resource cache directory
INFORMAZIONI: Decoding resources
AVVERTENZA: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7b060000
AVVERTENZA: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7b060000
AVVERTENZA: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x6e020000
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
GRAVE: Could not decode file, replacing by FALSE value: o/gu.9.png
INFORMAZIONI: Reading dex files
INFORMAZIONI: Merging .\app-release-unsigned.apk
AVVERTENZA: Skipping timeline-ads: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.twitter.android
AVVERTENZA: Skipping premium-icon-reddit: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.reddit.frontpage
AVVERTENZA: Skipping general-reddit-ads: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.reddit.frontpage
AVVERTENZA: Skipping pflotsh-ecmwf-subscription-unlock: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
AVVERTENZA: Skipping minimized-playback-music: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping tasteBuilder-remover: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping hide-get-premium: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
INFORMAZIONI: Skipping compact-header: Not explicitly included
AVVERTENZA: Skipping upgrade-button-remover: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping background-play: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping music-microg-support: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping music-video-ads: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping codecs-unlock: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping exclusive-audio-playback: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.apps.youtube.music
AVVERTENZA: Skipping promo-code-unlock: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with de.dwd.warnapp
AVVERTENZA: Skipping swipe-controls: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping downloads: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping seekbar-tapping: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping amoled: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping disable-create-button: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping hide-cast-button: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping return-youtube-dislike: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping hide-autoplay-button: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping premium-heading: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping custom-branding: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping disable-fullscreen-panels: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping old-quality-layout: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping hide-shorts-button: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping hide-watermark: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping sponsorblock: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping enable-wide-searchbar: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping tablet-mini-player: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping minimized-playback: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping client-spoof: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube, com.vanced.android.youtube
AVVERTENZA: Skipping custom-video-buffer: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping always-autorepeat: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping microg-support: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping settings: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
INFORMAZIONI: Skipping enable-debugging: Not explicitly included
AVVERTENZA: Skipping custom-playback-speed: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping hdr-auto-brightness: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping remember-video-quality: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping video-ads: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping general-ads: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
AVVERTENZA: Skipping hide-infocard-suggestions: Incompatible with com.ss.android.ugc.trill. This patch is only compatible with com.google.android.youtube
INFORMAZIONI: tiktok-download succeeded
INFORMAZIONI: tiktok-seekbar succeeded
INFORMAZIONI: tiktok-ads succeeded
INFORMAZIONI: Compiling resources
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:249: error: no definition for declared symbol 'com.ss.android.ugc.trill:animator/a'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:3557: error: no definition for declared symbol 'com.ss.android.ugc.trill:color/dz'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:3646: error: no definition for declared symbol 'com.ss.android.ugc.trill:color/gd'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:3647: error: no definition for declared symbol 'com.ss.android.ugc.trill:color/ge'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5865: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/a7'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5866: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/a8'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5867: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/a9'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5868: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/a_'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5869: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/aa'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5870: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/ab'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5871: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/ac'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5872: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/ad'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5873: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/ae'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:8116: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/clq'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:5946: error: no definition for declared symbol 'com.ss.android.ugc.trill:drawable/e_'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:23040: error: no definition for declared symbol 'com.ss.android.ugc.trill:layout/a00'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:23041: error: no definition for declared symbol 'com.ss.android.ugc.trill:layout/a01'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:23042: error: no definition for declared symbol 'com.ss.android.ugc.trill:layout/a02'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:23045: error: no definition for declared symbol 'com.ss.android.ugc.trill:layout/a05'.
AVVERTENZA: D:\Downloads\revanced patches\revanced-cache\res\values\public.xml:23046: error: no definition for declared symbol 'com.ss.android.ugc.trill:layout/a06'.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mirochu\AppData\Local\Temp\brut_util_Jar_155490079492164559491763792586019028481.tmp, link, -o, D:\Downloads\revanced patches\revanced-cache\aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 31, --version-code, 250602, --version-name, 25.6.2, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\mirochu\AppData\Local\Temp\APKTOOL17084108091046579827.tmp, -0, arsc, -I, revanced-cache\1.apk, --manifest, D:\Downloads\revanced patches\revanced-cache\AndroidManifest.xml, D:\Downloads\revanced patches\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:204)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mirochu\AppData\Local\Temp\brut_util_Jar_155490079492164559491763792586019028481.tmp, link, -o, D:\Downloads\revanced patches\revanced-cache\aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 31, --version-code, 250602, --version-name, 25.6.2, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\mirochu\AppData\Local\Temp\APKTOOL17084108091046579827.tmp, -0, arsc, -I, revanced-cache\1.apk, --manifest, D:\Downloads\revanced patches\revanced-cache\AndroidManifest.xml, D:\Downloads\revanced patches\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more
```

**Comment by oSumAtrIX** [comment]
Use the option `-r`
