### ISSUE TITLE
bug: CLI does not decode AndroidManifest.xml when it should 

### ISSUE THREAD

**Issue by reisxd** [revanced/revanced-cli#143]
### Type

Error at runtime

### Bug description

CLI won't decode AndroidManifest.xml even when it is supposed to.

### Steps to reproduce

I'm using Builder, which shouldn't matter too much because this is a bug in CLI/Patcher. But here's the command:

```bash
java -jar /home/codespace/revanced-builder/revanced/revanced-cli-v2.12.0.jar -b /home/codespace/revanced-builder/revanced/revanced-patches-v2.69.3.jar -t ./revanced-cache --experimental -a /home/codespace/revanced-builder/revanced/youtube.music.apk -o /home/codespace/revanced-builder/revanced/revanced.apk -i exclusive-audio-playback -i codecs-unlock -i music-microg-support -i music-video-ads -i tasteBuilder-remover -i minimized-playback-music -i upgrade-button-remover -i hide-get-premium -i background-play -e compact-header
```

### Relevant log output

```shell
[builder] INFO: Reading dex files
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFO: exclusive-audio-playback succeeded
[builder] INFO: codecs-unlock succeeded
[builder] SEVERE: music-microg-support failed:
[builder] app.revanced.patcher.patch.PatchResultError: 'music-microg-support' depends on 'music-microg-support' but the following error was raised: java.io.FileNotFoundException: ./revanced-cache/AndroidManifest.xml (No such file or directory)
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:259)
at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:46)
at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:383)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24)
at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
at picocli.CommandLine.access$1300(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFO: music-video-ads succeeded
[builder] INFO: tasteBuilder-remover succeeded
[builder] INFO: minimized-playback-music succeeded
[builder] INFO: upgrade-button-remover succeeded
[builder] INFO: hide-get-premium succeeded
[builder] INFO: background-play succeeded
[builder] INFO: Not compiling resources because resource patching is not required
[builder] INFO: Writing modified dex files
[builder] INFO: Writing dex file classes4.dex
[builder] INFO: Writing dex file classes2.dex
[builder] INFO: Writing dex file classes3.dex
[builder] INFO: Writing dex file classes.dex
[builder] INFO: Writing dex file classes5.dex
[builder] INFO: Aligning revanced_raw.apk to revanced_aligned.apk
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] INFO: Found existing keystore: revanced.keystore
[builder] INFO: Copying revanced_signed.apk to revanced.apk
[builder] INFO: Finished
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Fixed in https://github.com/revanced/revanced-patcher/commit/9c07ffcc7af9f088426528561f4321c5cc6b5b15.
