### ISSUE TITLE
bug: CLI showing error

### ISSUE THREAD

**Issue by Cypher-Emm** [revanced/revanced-cli#149]
### Type

Error while running the CLI

### Bug description

During patching with new version of cli v2.14.0 i am getting an error. The logs for the same are below. The other two versions before this one also used not to work properly with mounting issues and some patches failing.
I am Using an armv7 device  running Android 11 and patching base apk on win 10 with open jdk17.

### Steps to reproduce

Get all the required files for patching(latest versions as of now)
Get a base.apk of yt to patch.
Start patching and the cli will throw an error

### Relevant log output

```shell
PS D:\ReVanced> java -jar revanced-cli-all.jar -a base.apk -c -d RZ8M323KEHE -o revanced.apk -m integrations.apk -b revanced-patches.jar -e microg-support -e custom-branding -e disable-create-button -e theme -e hide-shorts-button -e premium-heading -e enable-debugging -e custom-playback-speed -e return-youtube-dislike -e downloads -e hdr-auto-brightness --mount
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20)
        at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 22 more
```

### Solution

..

### Additional context

..

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Fixed.
