### ISSUE TITLE
bug: Patches are not working in Revanced CLI

### ISSUE THREAD

**Issue by berndt-toast83** [revanced/revanced-cli#150]
### Type

Error at runtime

### Bug description

Using the Revanced Builder, which uses the Revanced CLI, it is failing when trying to apply patches

### Steps to reproduce

Follow the steps to patch an PK here: https://github.com/reisxd/revanced-builder/wiki/How-to-use-revanced-builder-on-Android

### Relevant log output

```shell
[builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ... 22 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are using an old version of the CLI or patches, update them.
