### ISSUE TITLE
Patches successfully, but can't open Youtube app after. Freeezing and stuttering occurs. 

### ISSUE THREAD

**Issue by lowendgamer** [revanced/revanced-cli#151]
### Type

Other

### Bug description

It patches successfully, but I can't open Youtube app after. It freezes and stutters prompting me to force close the app.

### Steps to reproduce

The newer prebuilt packages maybe seem to be the cause of the problem. I patched it before with older prebuilts a month ago, and it was working just fine. 

### Relevant log output

```shell
ptrck@msi:~/Downloads/Qwerty$ adb devices
List of devices attached
3a6baa05	device

ptrck@msi:~/Downloads/Qwerty$ java -jar revanced-cli-all.jar -a youtube.apk -m integrations.apk -c -d 3a6baa05 -o revanced.apk -b revanced-patches.jar -e microg-support --mount
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging integrations.apk 
WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage 
WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage 
WARNING: Skipping hide-premium-navbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music 
WARNING: Skipping disable-capture-restriction, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music 
WARNING: Skipping spotify-theme, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music 
WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp 
WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a 
WARNING: Skipping tiktok-speed, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically 
WARNING: Skipping monochrome-icon, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android 
WARNING: Skipping dynamic-color, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android 
WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android 
WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
INFO: Skipping compact-header, reason: excluded by default 
WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
INFO: Skipping enable-debugging, reason: excluded by default 
INFO: Skipping microg-support, reason: manually excluded 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: swipe-controls succeeded 
INFO: downloads succeeded 
INFO: seekbar-tapping succeeded 
INFO: remember-video-quality succeeded 
INFO: custom-playback-speed succeeded 
INFO: minimized-playback succeeded 
INFO: client-spoof succeeded 
INFO: custom-video-buffer succeeded 
INFO: settings succeeded 
INFO: hdr-auto-brightness succeeded 
INFO: always-autorepeat succeeded 
INFO: general-ads succeeded 
INFO: hide-infocard-suggestions succeeded 
INFO: video-ads succeeded 
INFO: hide-time-and-seekbar succeeded 
INFO: old-quality-layout succeeded 
INFO: enable-wide-searchbar succeeded 
INFO: disable-fullscreen-panels succeeded 
INFO: hide-autoplay-button succeeded 
INFO: disable-startup-shorts-player succeeded 
SEVERE: premium-heading failed: 
app.revanced.patcher.patch.PatchResultError: The file revanced-cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
	at app.revanced.patches.youtube.layout.branding.header.patch.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:40)
	at app.revanced.patches.youtube.layout.branding.header.patch.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:19)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:342)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: custom-branding succeeded 
INFO: hide-create-button succeeded 
INFO: hide-shorts-button succeeded 
INFO: hide-video-buttons succeeded 
INFO: theme succeeded 
INFO: hide-email-address succeeded 
INFO: sponsorblock succeeded 
INFO: hide-cast-button succeeded 
INFO: tablet-mini-player succeeded 
INFO: return-youtube-dislike succeeded 
INFO: hide-watermark succeeded 
INFO: disable-auto-player-popup-panels succeeded 
INFO: disable-auto-captions succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Writing dex file classes2.dex 
INFO: Writing dex file classes.dex 
INFO: Writing dex file classes3.dex 
INFO: Writing dex file classes4.dex 
INFO: Writing dex file classes8.dex 
INFO: Writing dex file classes5.dex 
INFO: Writing dex file classes6.dex 
INFO: Writing dex file classes7.dex 
INFO: Writing resources... 
INFO: Aligning revanced_raw.apk to revanced_aligned.apk 
INFO: Copying revanced_aligned.apk to revanced.apk 
INFO: Cleaned up cache directory 
INFO: Installing by mounting 
10-10 21:20:40.527 22737 22737 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:40.533 22737 22737 I AndroidRuntime: Using default boot image
10-10 21:20:40.533 22737 22737 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:40.712 22737 22737 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:40.714 22737 22737 D AndroidRuntime: Shutting down VM
10-10 21:20:40.738 22749 22749 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:40.741 22749 22749 I AndroidRuntime: Using default boot image
10-10 21:20:40.741 22749 22749 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:40.902 22749 22749 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:40.903 22749 22749 D AndroidRuntime: Shutting down VM
10-10 21:20:41.838 22784 22784 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:41.842 22784 22784 I AndroidRuntime: Using default boot image
10-10 21:20:41.842 22784 22784 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:42.001 22784 22784 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:42.003 22784 22784 D AndroidRuntime: Shutting down VM
10-10 21:20:42.939 22805 22805 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:42.943 22805 22805 I AndroidRuntime: Using default boot image
10-10 21:20:42.943 22805 22805 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:43.101 22805 22805 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:43.103 22805 22805 D AndroidRuntime: Shutting down VM
10-10 21:20:43.580 22711 22711 D AndroidRuntime: Shutting down VM
10-10 21:20:43.581 22711 22711 E AndroidRuntime: FATAL EXCEPTION: main
10-10 21:20:43.581 22711 22711 E AndroidRuntime: Process: com.google.android.youtube, PID: 22711
10-10 21:20:43.581 22711 22711 E AndroidRuntime: java.lang.NoClassDefFoundError: poe
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at qvu.A(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at szv.ax(PG:3)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.b(PG:88)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.a(PG:38)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at aqkt.a(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.d(PG:23)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.a(PG:28)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at aqkt.a(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at enm.f(PG:3)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.d(PG:24)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.a(PG:28)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at aqkt.a(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehy.hg(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehx.b(Unknown Source:3881)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehx.a(PG:2)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at eit.onCreate(PG:48)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: Caused by: java.lang.VerifyError: Verifier rejected class poe: rql poe.f(java.lang.String, com.google.android.libraries.youtube.ads.model.InstreamAdBreak, j$.util.Optional, java.util.List) failed to verify: rql poe.f(java.lang.String, com.google.android.libraries.youtube.ads.model.InstreamAdBreak, j$.util.Optional, java.util.List): [0xB] returning 'Precise Reference: java.util.ArrayList', but expected from declaration 'Precise Reference: rql' (declaration of 'poe' appears in /data/app/~~ksyO06E_utHBqUaaKOnRdQ==/com.google.android.youtube-MizHd0gNaaguVS2Sa8i6hQ==/base.apk!classes3.dex)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at qvu.A(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at szv.ax(PG:3)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.b(PG:88)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.a(PG:38)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at aqkt.a(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.o(PG:91)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at ehv.a(PG:30)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at aqkt.a(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at qfd.call(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at uig.i(PG:1)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at edr.run(PG:28)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at syy.run(PG:7)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at nrq.run(PG:5)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at nru.run(PG:23)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at mwd.run(PG:6)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
10-10 21:20:43.581 22711 22711 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
10-10 21:20:44.036 22863 22863 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:44.040 22863 22863 I AndroidRuntime: Using default boot image
10-10 21:20:44.040 22863 22863 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:44.217 22863 22863 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:44.220 22863 22863 D AndroidRuntime: Shutting down VM
10-10 21:20:45.152 22884 22884 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:45.156 22884 22884 I AndroidRuntime: Using default boot image
10-10 21:20:45.156 22884 22884 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:45.324 22884 22884 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:45.326 22884 22884 D AndroidRuntime: Shutting down VM
10-10 21:20:46.282 22904 22904 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:46.285 22904 22904 I AndroidRuntime: Using default boot image
10-10 21:20:46.285 22904 22904 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:46.457 22904 22904 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:46.458 22904 22904 D AndroidRuntime: Shutting down VM
10-10 21:20:47.376 22924 22924 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:47.380 22924 22924 I AndroidRuntime: Using default boot image
10-10 21:20:47.380 22924 22924 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:47.552 22924 22924 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:47.553 22924 22924 D AndroidRuntime: Shutting down VM
10-10 21:20:48.502 22945 22945 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:48.506 22945 22945 I AndroidRuntime: Using default boot image
10-10 21:20:48.506 22945 22945 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:48.682 22945 22945 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:48.684 22945 22945 D AndroidRuntime: Shutting down VM
10-10 21:20:49.617 22966 22966 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:49.621 22966 22966 I AndroidRuntime: Using default boot image
10-10 21:20:49.621 22966 22966 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:49.795 22966 22966 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:49.797 22966 22966 D AndroidRuntime: Shutting down VM
10-10 21:20:50.739 22987 22987 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:50.743 22987 22987 I AndroidRuntime: Using default boot image
10-10 21:20:50.743 22987 22987 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:50.915 22987 22987 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:50.917 22987 22987 D AndroidRuntime: Shutting down VM
10-10 21:20:51.841 23007 23007 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:51.845 23007 23007 I AndroidRuntime: Using default boot image
10-10 21:20:51.845 23007 23007 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:52.017 23007 23007 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:52.018 23007 23007 D AndroidRuntime: Shutting down VM
10-10 21:20:52.982 23028 23028 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:52.986 23028 23028 I AndroidRuntime: Using default boot image
10-10 21:20:52.986 23028 23028 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:53.164 23028 23028 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:53.166 23028 23028 D AndroidRuntime: Shutting down VM
10-10 21:20:54.082 23049 23049 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:54.086 23049 23049 I AndroidRuntime: Using default boot image
10-10 21:20:54.086 23049 23049 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:54.264 23049 23049 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:54.266 23049 23049 D AndroidRuntime: Shutting down VM
10-10 21:20:55.177 23069 23069 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:55.181 23069 23069 I AndroidRuntime: Using default boot image
10-10 21:20:55.181 23069 23069 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:55.349 23069 23069 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:55.354 23069 23069 D AndroidRuntime: Shutting down VM
10-10 21:20:56.282 23092 23092 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:56.286 23092 23092 I AndroidRuntime: Using default boot image
10-10 21:20:56.287 23092 23092 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:56.445 23092 23092 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:56.446 23092 23092 D AndroidRuntime: Shutting down VM
10-10 21:20:57.373 23120 23120 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:57.376 23120 23120 I AndroidRuntime: Using default boot image
10-10 21:20:57.377 23120 23120 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:57.539 23120 23120 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:57.542 23120 23120 D AndroidRuntime: Shutting down VM
10-10 21:20:58.470 23141 23141 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:58.476 23141 23141 I AndroidRuntime: Using default boot image
10-10 21:20:58.476 23141 23141 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:58.642 23141 23141 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:58.644 23141 23141 D AndroidRuntime: Shutting down VM
10-10 21:20:59.551 23163 23163 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:20:59.555 23163 23163 I AndroidRuntime: Using default boot image
10-10 21:20:59.555 23163 23163 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:20:59.727 23163 23163 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:20:59.729 23163 23163 D AndroidRuntime: Shutting down VM
10-10 21:21:00.625 23186 23186 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:00.629 23186 23186 I AndroidRuntime: Using default boot image
10-10 21:21:00.629 23186 23186 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:00.803 23186 23186 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:00.804 23186 23186 D AndroidRuntime: Shutting down VM
10-10 21:21:01.688 23209 23209 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:01.692 23209 23209 I AndroidRuntime: Using default boot image
10-10 21:21:01.692 23209 23209 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:01.862 23209 23209 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:01.864 23209 23209 D AndroidRuntime: Shutting down VM
10-10 21:21:02.752 23232 23232 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:02.756 23232 23232 I AndroidRuntime: Using default boot image
10-10 21:21:02.756 23232 23232 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:02.926 23232 23232 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:02.928 23232 23232 D AndroidRuntime: Shutting down VM
10-10 21:21:03.854 23253 23253 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:03.858 23253 23253 I AndroidRuntime: Using default boot image
10-10 21:21:03.858 23253 23253 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:04.031 23253 23253 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:04.033 23253 23253 D AndroidRuntime: Shutting down VM
10-10 21:21:04.904 23276 23276 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:04.908 23276 23276 I AndroidRuntime: Using default boot image
10-10 21:21:04.908 23276 23276 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:05.075 23276 23276 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:05.077 23276 23276 D AndroidRuntime: Shutting down VM
10-10 21:21:05.964 23299 23299 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:05.968 23299 23299 I AndroidRuntime: Using default boot image
10-10 21:21:05.968 23299 23299 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:06.141 23299 23299 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:06.142 23299 23299 D AndroidRuntime: Shutting down VM
10-10 21:21:07.097 23322 23322 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:07.101 23322 23322 I AndroidRuntime: Using default boot image
10-10 21:21:07.101 23322 23322 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:07.280 23322 23322 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:07.281 23322 23322 D AndroidRuntime: Shutting down VM
10-10 21:21:08.216 23357 23357 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:08.220 23357 23357 I AndroidRuntime: Using default boot image
10-10 21:21:08.220 23357 23357 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:08.396 23357 23357 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:08.398 23357 23357 D AndroidRuntime: Shutting down VM
10-10 21:21:09.321 23378 23378 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:09.331 23378 23378 I AndroidRuntime: Using default boot image
10-10 21:21:09.331 23378 23378 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:09.506 23378 23378 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:09.508 23378 23378 D AndroidRuntime: Shutting down VM
10-10 21:21:10.411 23403 23403 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:10.414 23403 23403 I AndroidRuntime: Using default boot image
10-10 21:21:10.414 23403 23403 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:10.574 23403 23403 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:10.576 23403 23403 D AndroidRuntime: Shutting down VM
10-10 21:21:11.507 23426 23426 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:11.511 23426 23426 I AndroidRuntime: Using default boot image
10-10 21:21:11.511 23426 23426 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:11.688 23426 23426 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:11.692 23426 23426 D AndroidRuntime: Shutting down VM
10-10 21:21:12.613 23450 23450 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:12.617 23450 23450 I AndroidRuntime: Using default boot image
10-10 21:21:12.617 23450 23450 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:12.785 23450 23450 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:12.788 23450 23450 D AndroidRuntime: Shutting down VM
10-10 21:21:13.659 23475 23475 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:13.664 23475 23475 I AndroidRuntime: Using default boot image
10-10 21:21:13.664 23475 23475 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:13.834 23475 23475 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:13.836 23475 23475 D AndroidRuntime: Shutting down VM
10-10 21:21:14.751 23513 23513 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:14.755 23513 23513 I AndroidRuntime: Using default boot image
10-10 21:21:14.755 23513 23513 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:14.924 23513 23513 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:14.926 23513 23513 D AndroidRuntime: Shutting down VM
10-10 21:21:14.931 23513 23530 I AndroidRuntime: NOTE: attach of thread 'Binder:23513_2' failed
10-10 21:21:15.845 23539 23539 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:15.849 23539 23539 I AndroidRuntime: Using default boot image
10-10 21:21:15.849 23539 23539 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:16.025 23539 23539 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:16.026 23539 23539 D AndroidRuntime: Shutting down VM
10-10 21:21:16.932 23562 23562 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-10 21:21:16.936 23562 23562 I AndroidRuntime: Using default boot image
10-10 21:21:16.936 23562 23562 I AndroidRuntime: Leaving lock profiling enabled
10-10 21:21:17.100 23562 23562 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-10 21:21:17.102 23562 23562 D AndroidRuntime: Shutting down VM
INFO: Stopped logging because the app was closed 
ptrck@msi:~/Downloads/Qwerty$
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Fixed.

**Comment by lowendgamer** [comment]
> Fixed.

Should I re-download all the prebuilt packages?
