### ISSUE TITLE
bug: com.android.apksig.apk.ApkFormatException: Multiple ZIP entries with the same name: META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by jaum20** [revanced/revanced-cli#156]
### Type

Error while running the CLI

### Bug description

I can't patch the TikTok apk

### Steps to reproduce

run `java -jar revanced-cli-2.14.0-all.jar -a com.ss.android.ugc.trill_26.5.5-260505_minAPI21\(arm64-v8a,armeabi-v7a\)\(nodpi\)_apkmirror.com.apk -o revanced_tt.apk -b revanced-patches-2.81.10.jar`

### Relevant log output

```shell
(...) Found existing keystore: revanced_tt_int.keystore 
com.android.apksig.apk.ApkFormatException: Multiple ZIP entries with the same name: META-INF/MANIFEST.MF
	at com.android.apksig.ApkSigner.parseZipCentralDirectory(ApkSigner.java:825)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:249)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:204)
	at app.revanced.utils.signing.Signer.signApk(Signer.kt:77)
	at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:168)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Your apk file is corrupted.
