### ISSUE TITLE
bug: patcher still enabling resource patching when it shouldn't

### ISSUE THREAD

**Issue by reisxd** [revanced/revanced-cli#171]
### Type

Error while running the CLI

### Bug description

ReVanced CLI/Patcher enables resource patching when it shouldn't.

### Steps to reproduce

I have used Builder but it shouldn't matter, because I can reproduce an issue someone was having a few days ago.

1. Download the latest stuff
2. Run `java -jar /workspaces/revanced-builder/revanced/revanced-cli-v2.16.1.jar -b /workspaces/revanced-builder/revanced/revanced-patches-v2.142.0.jar -t ./revanced-cache --experimental -a /workspaces/revanced-builder/revanced/frontpage.apk -o /workspaces/revanced-builder/revanced/revanced.apk -i general-reddit-ads -i premium-icon-reddit`

### Relevant log output

```shell
[builder] INFO: Reading dex files
[builder] WARNING: Skipping package group: com.reddit.frontpage
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=sharedUserLabel, value=0x7f130d5d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161e
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f131620
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140019
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100002
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=fullBackupContent, value=0x7f160001
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=networkSecurityConfig, value=0x7f160006
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=dataExtractionRules, value=0x7f160004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=localeConfig, value=0x7f160005
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401c4
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100036
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100005
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100003
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003e
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100039
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100033
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100035
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100034
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100037
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100038
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100002
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130d84
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401c2
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cd
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130d90
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130ad5
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f14001d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f13010a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161e
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f131620
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130ce1
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130d84
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130e20
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x7f13147b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130afa
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x7f131479
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160014
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160013
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f130285
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f130201
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130ad6
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f13124b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1402c9
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f03002f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x7f13147a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f14015a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f14015a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1402bb
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140177
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140177
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f0c0012
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050006
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050005
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050004 WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140308 WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401e1
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f160015
[builder] INFO: Skipping sim-spoof, reason: excluded by default
[builder] INFO: Skipping compact-header, reason: excluded by default
[builder] INFO: Skipping debug-mode, reason: excluded by default
[builder] INFO: Skipping theme, reason: excluded by default
[builder] WARNING: Skipping predictive-back-gesture, reason: Missing compatibility annotation. Continuing.
[builder] WARNING: Skipping package group: com.reddit.frontpage
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=sharedUserLabel, value=0x7f130d5d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161e
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f131620
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140019
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100002
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=fullBackupContent, value=0x7f160001
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=networkSecurityConfig, value=0x7f160006
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=dataExtractionRules, value=0x7f160004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=localeConfig, value=0x7f160005
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401c4
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100036
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100005
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100003
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003e
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10003d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100039
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001b WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100033
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100035
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100034
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100037
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f10001a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100038
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100002
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130d84
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401c2
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cd WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1301da WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130d90
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130ad5
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f14001d
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f13010a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f13161e
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x7f131620
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130ce1
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130d84
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401cc
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130e20
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x7f13147b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130afa
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x7f131479
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160014
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f160013
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f130285
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f130201
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f130ad6
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f13124b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140000
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1402c9
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f03002f
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x7f13147a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f16000b
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f14015a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f14015a
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1402bb
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140167
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140177
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140177
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f0c0012
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050006
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050005
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0x7f050004
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f140308
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1401e1
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f160015
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=app, name=fontFamily, value=0x800b008c
[builder] WARNING: Could not decode attr value, using undecoded value instead: ns=app, name=fontFamily, value=0x800b008c
[builder] brut.androlib.err.CantFindFrameworkResException: Can't find framework resources for package of id: 127 at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:822) at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:113) at brut.androlib.res.data.ResTable.getPackage(ResTable.java:81) at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:64) at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:60) at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:59) at brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:70) at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:47) at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:745) at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:257) at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140) at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:228) at app.revanced.patcher.Patcher.access$decodeResources(Patcher.kt:36) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:348) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
ˋpredictive-back-gestureˋ is a resource patch. The cli output is fixed already in the dev branch, open a new issue for that if you want to track that and add it to the dev merge pr to autoclose it.
