### ISSUE TITLE
Error Patching Twitter v9.68.1-release.0

### ISSUE THREAD

**Issue by Solus32** [revanced/revanced-cli#177]
### Type

Error while running the CLI

### Bug description

Error while patching the last version of Twitter v9.68.1-release.0 from apkmirror , the same ocurr using ReVanced Manager.

### Steps to reproduce

java -jar revanced-cli-2.18.0-all.jar -a com.twitter.android_9.68.1.apk -c -o twitter-revanced_v9.68.1.apk -b revanced-patches-2.144.0.jar -m app-release-unsigned.apk -e dynamic-color -e monochrome-icon -e predictive-back-gesture

### Relevant log output

```shell
INFORMACIÓN: Reading dex files 
INFORMACIÓN: Decoding AndroidManifest.xml only, because resources are not needed 
INFORMACIÓN: Merging app-release-unsigned.apk 
INFORMACIÓN: Skipping compact-header: Excluded by default 
INFORMACIÓN: Skipping debug-mode: Excluded by default 
INFORMACIÓN: Skipping dynamic-color: Manually excluded 
INFORMACIÓN: Skipping monochrome-icon: Manually excluded 
INFORMACIÓN: Skipping predictive-back-gesture: Manually excluded 
INFORMACIÓN: Skipping sim-spoof: Excluded by default 
INFORMACIÓN: Skipping theme: Excluded by default 
INFORMACIÓN: timeline-ads succeeded 
INFORMACIÓN: Not compiling resources because resource patching is not required 
INFORMACIÓN: Writing modified dex files 
INFORMACIÓN: Aligning com.twitter.android_9.68.1.apk to twitter-revanced_v9.68.1_aligned.apk 
INFORMACIÓN: Signing twitter-revanced_v9.68.1_aligned.apk to twitter-revanced_v9.68.1_signed.apk 
java.security.KeyStoreException: BKS not found
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:922)
	at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:27)
	at app.revanced.utils.signing.Signer.signApk(Signer.kt:58)
	at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: BKS for provider BC
	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:87)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.base/java.security.Security.getImpl(Security.java:743)
	at java.base/java.security.KeyStore.getInstance(KeyStore.java:919)
	... 13 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Solus32** [comment]
I use Azul Zulu 17.0.5
