### ISSUE TITLE
bug: PatchResultError when applying patches

### ISSUE THREAD

**Issue by ledoqsang2103** [revanced/revanced-cli#182]
### Type

Error while running the CLI

### Bug description

This bug occurs every time when using CLI.
```
SEVERE: return-youtube-dislike failed:
app.revanced.patcher.patch.PatchResultError
```

### Steps to reproduce

- revanced-cli v2.18.2
- revanced-patches v2.146.0
- Youtube v17.49.37
Patch Youtube app (non-root)

### Relevant log output

```shell
SEVERE: return-youtube-dislike failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55)
        at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425)
        ... 16 more
```

### Screenshots or videos

![Screenshot_20221220_095135](https://user-images.githubusercontent.com/116613471/208570516-882a678e-f4d3-49ee-8386-90ece34f71a5.png)
![Screenshot_20221220_100116](https://user-images.githubusercontent.com/116613471/208571647-5f8ac223-a62d-45d8-8c50-c059f8dad316.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
This is unrelated to CLI, the patch is failing, the appropriate repository for this issue is https://github.com/revanced/revanced-patches

**Comment by oSumAtrIX** [comment]
@Ushie it's actually not wrong, the patches are fine, though the latest commit to the CLI is not released yet.

**Comment by ledoqsang2103** [comment]
Thanks for replying to me, thanks all for your work, I'm looking forward to the group's next commit!
Sorry for posting Issue in wrong repository!

**Comment by Ushie** [comment]
> @Ushie it's actually not wrong, the patches are fine, though the latest commit to the CLI is not released yet.

I see
