### ISSUE TITLE
bug: Cannot use ReVanced Manager Keystore with cli

### ISSUE THREAD

**Issue by RehanPlayz** [revanced/revanced-cli#198]
### Type

Error while running the CLI

### Bug description

Using the ReVanced Manager Keystore with the cli gives an error

### Steps to reproduce

Using the ReVanced Manager Keystore with the cli 

### Relevant log output

```shell
INFO: Found existing keystore: revanced-manager.keystore
java.security.UnrecoverableKeyException: no match
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.getObject(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineGetKey(Unknown Source)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1050)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:68)
        at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The ReVanced CLI and ReVanced Manager are incompatible and not designed to work interchangeably in mind yet.
