### ISSUE TITLE
bug: CLI crashes when called

### ISSUE THREAD

**Issue by UndarkAido** [revanced/revanced-cli#202]
### Type

Error while running the CLI

### Bug description

I'm setting up a fresh phone and saw that the manager wasn't supported anymore so I thought I'd give the CLI tool a fresh shot, but I got the following. What am I doing wrong?

### Steps to reproduce

1. Run `.\zulu17.40.19-ca-jdk17.0.6-win_x64\bin\java.exe -jar .\revanced-cli-2.20.0-all.jar -b "revanced-cli-2.20.0-all.jar" -a ".\com.google.android.youtube_18.03.36-1535632832_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk" -l`

### Relevant log output

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:21)
        at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:39)
        at app.revanced.cli.command.MainCommand.printListOfPatches(MainCommand.kt:218)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:124)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You must pass the patches jar to the option `-b`. Check `--help`.

**Comment by UndarkAido** [comment]
Oh, oops. Sorry to bother you.
