### ISSUE TITLE
bug: revanced cli fails to build most recent patches

### ISSUE THREAD

**Issue by Sivecano** [revanced/revanced-cli#209]
### Type

Error while running the CLI

### Bug description

applying patches with the "integrations" dependency throws an error. but as I understand it, Integrations is a seperate application? so perhaps this shouldn't happen?

### Steps to reproduce

1. download the most recent releases of revanced-cli and revanced-patches
2. try to apply them to youtube 18.03,36

### Relevant log output

```shell
SEVERE: always-autorepeat failed: 
app.revanced.patcher.patch.PatchResultError: 'always-autorepeat' depends on 'integrations' but the following error was raised: Integrations have not been merged yet. This patch can not succeed without merging the integrations.
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
(and so forth but it really does fail for a majority of the patches in this manner)
```

### Solution

as it seems to me perhaps integrations should be an exception or something

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Integrations have not been merged yet. That patch can not succeed without merging the integrations.

**Comment by oSumAtrIX** [comment]
You need to merge this with the CLI: https://github.com/revanced/revanced-integrations

**Comment by Sivecano** [comment]
aight

**Comment by Sivecano** [comment]
> You need to merge this with the CLI: https://github.com/revanced/revanced-integrations

like merge it with the cli tool itself?

**Comment by oSumAtrIX** [comment]
Yeah, check the note below here: https://github.com/revanced/revanced-cli/blob/main/docs/1_usage.md

**Comment by Sivecano** [comment]
> Yeah, check the note below here: https://github.com/revanced/revanced-cli/blob/main/docs/1_usage.md

works, thanks for your time

**Comment by oSumAtrIX** [comment]
Np
