### ISSUE TITLE
Stuck on Compiling resources

### ISSUE THREAD

**Issue by einekratzekatze** [revanced/revanced-cli#211]
### Type

Error while running the CLI

### Bug description

See log output / Steps

### Steps to reproduce

Try to patch a TikTok APK (tried 28.8.3 and 28.8.2) with the patches I used (-i hide-ads -i playback-speed -i predictive-back-gesture -i show-seekbar) or probably any patches. 

### Relevant log output

```shell
PS C:\Users\USER\Downloads> java -jar revanced-cli-2.20.1-all.jar -a .\tiktok-28-8-3.apk -b .\revanced-patches-2.166.0.jar -o Tiktokpatched.apk --exclusive -i hide-ads -i playback-speed -i predictive-back-gesture -i show-seekbar
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
INFO: Skipping disable-login-requirement: Excluded by default
WARNING: Skipping downloads: Incompatible with version 28.8.3. This patch is only compatible with version com.ss.android.ugc.trill: 27.8.3;com.zhiliaoapp.musically: 27.8.3
WARNING: Skipping feed-filter: Incompatible with version 28.8.3. This patch is only compatible with version com.ss.android.ugc.trill: 27.8.3;com.zhiliaoapp.musically: 27.8.3
INFO: Skipping fix-google-login: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
WARNING: Skipping settings: Incompatible with version 28.8.3. This patch is only compatible with version com.ss.android.ugc.trill: 27.8.3;com.zhiliaoapp.musically: 27.8.3
WARNING: Skipping sim-spoof: Incompatible with version 28.8.3. This patch is only compatible with version com.ss.android.ugc.trill: 27.8.3;com.zhiliaoapp.musically: 27.8.3
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "o/gx.9.png". Renaming it to *.png.
INFO: hide-ads succeeded
INFO: playback-speed succeeded
INFO: predictive-back-gesture succeeded
INFO: show-seekbar succeeded
INFO: Compiling resources
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a0.xml:2: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a0.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a1.xml:3: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a1.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a2.xml:2: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a2.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a3.xml:2: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a3.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a4.xml:2: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a4.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a5.xml:2: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a5.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a6.xml:2: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a6.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a7.xml:3: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a7.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a8.xml:3: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a8.xml: error: file failed to compile.
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a9.xml:3: error: not well-formed (invalid token).
WARNING: C:\Users\theod\Downloads\revanced-cache\res\anim\a9.xml: error: file failed to compile.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are patching the wrong versions. Also the warnings shouldn't cause any issues.

**Comment by einekratzekatze** [comment]
> You are patching the wrong versions. Also the warnings shouldn't cause any issues. You can try supplying aapt over the CLI options.
My bad, it wasn't stuck, it gave me this Error after a while
```
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\theod\AppData\Local\Temp\brut_util_Jar_95184835309283863643940780002167120500.tmp, compile, --dir, C:\Users\theod\Downloads\revanced-cache\res, --legacy, -o, C:\Users\theod\Downloads\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
        at app.revanced.patcher.Patcher.save(Patcher.kt:126)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\theod\AppData\Local\Temp\brut_util_Jar_95184835309283863643940780002167120500.tmp, compile, --dir, C:\Users\theod\Downloads\revanced-cache\res, --legacy, -o, C:\Users\theod\Downloads\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
        ... 13 more
```

**Comment by Axelen123** [comment]
aapt is having problems again like always. Try without predictive-back-gesture for now. We will eventually switch to arsclib, which doesn't have this problem.
