### ISSUE TITLE
bug: <Error compiling revanced-cli project>

### ISSUE THREAD

**Issue by jhcarlos8888** [revanced/revanced-cli#215]
### Type

Error while running the CLI

### Bug description

When I try to compile the revanced-cli project I get an error called java.nio.file.NoSuchFileException. The configuration I have to be able to compile the project is as follows:

`<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="MainKt" type="JetRunConfigurationType">
    <option name="MAIN_CLASS_NAME" value="app.revanced.cli.main.MainKt" />
    <module name="revanced-cli.main" />
    <option name="PROGRAM_PARAMETERS" value="
         --options ../options.toml
         -o ../revanced.apk
         -a ../binaries/unpatched-input.apk
         -t ../revanced-cache
         -b ../revanced-patches/build/libs/revanced-patches-<version>.jar
         -m ../revanced-integrations/app/build/outputs/apk/release/revanced-integrations-<version>.apk
         -d device-name"
    />
    <shortenClasspath name="NONE" />
    <method v="2">
      <option name="RunConfigurationTask" enabled="true" run_configuration_name="revanced-patcher [publish]" run_configuration_type="GradleRunConfiguration" />
      <option name="RunConfigurationTask" enabled="true" run_configuration_name="revanced-patches [build]" run_configuration_type="GradleRunConfiguration" />
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>`

### Steps to reproduce

When trying to compile and run the project with the RUN option it immediately generates an error

### Relevant log output

```shell
I present the log that is generated at the time of the error

"C:\Program Files\Java\zulu17.42.19-ca-jdk17.0.7\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1\lib\idea_rt.jar=54943:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\SoporteTI\Documents\Proyectos Programacion\ProyectoRevanced\revanced-cli\build\classes\kotlin\main;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\revanced-patcher\7.0.0\8400a366b91481ca4a387a79c0476b810791938f\revanced-patcher-7.0.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.8.10\7c002ac41f547a82e81dfebd2a20577a738dbf3f\kotlin-stdlib-jdk8-1.8.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.8.10\1e90b778ea4669b6bcbfaca57313665ddd804779\kotlin-reflect-1.8.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\info.picocli\picocli\4.7.1\7ac5efc1f895a237eb3d8e77375d7c7a7dbbaae7\picocli-4.7.1.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.github.revanced\jadb\master-SNAPSHOT\db2a5ce80201536ff3e9d1caf2f4f5dc410e3c53\jadb-master-SNAPSHOT.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.android.tools.build\apksig\7.2.2\735df93a1e8f80050ce1e23caf72edd493273970\apksig-7.2.2.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcpkix-jdk15on\1.70\f81e5af49571a9d5a109a88f239a73ce87055417\bcpkix-jdk15on-1.70.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\cc.ekblad\4koma\1.1.0\9f9a283c0c1f8b5cbf6838b113b4c99657feb092\4koma-1.1.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.8.10\cb726a23c808a850a43e7d6b9d1ba91b02fe9f05\kotlin-stdlib-jdk7-1.8.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.8.10\6d5560a229477df9406943d5feda5618e98eb64c\kotlin-stdlib-1.8.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.mockito\mockito-core\2.28.2\91110215a8cb9b77a46e045ee758f77d79167cc0\mockito-core-2.28.2.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcutil-jdk15on\1.70\54280e7195a7430d7911ded93fc01e07300b9526\bcutil-jdk15on-1.70.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.70\4636a0d01f74acaf28082fb62b317f1080118371\bcprov-jdk15on-1.70.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.8.10\a61b182458550492c12aee66157d7b524a63a5ec\kotlin-stdlib-common-1.8.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\net.bytebuddy\byte-buddy\1.9.10\211a2b4d3df1eeef2a6cacf78d74a1f725e7a840\byte-buddy-1.9.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\net.bytebuddy\byte-buddy-agent\1.9.10\9674aba5ee793e54b864952b001166848da0f26b\byte-buddy-agent-1.9.10.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\2.6\639033469776fd37c08358c6b92a4761feb2af4b\objenesis-2.6.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\apktool-lib\2.7.0\a35ef51c89901149f6420e15eace9723a188b6ac\apktool-lib-2.7.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\xpp3\xpp3\1.1.4c\9b988ea84b9e4e9f1874e390ce099b8ac12cfff5\xpp3-1.1.4c.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\smali\2.5.3-a3836654\61550aa32e1e837b5f4e0297272194cdf7925775\smali-2.5.3-a3836654.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\multidexlib2\2.5.3-a3836654\ba71982be11da07754898ff0d0f774104039122e\multidexlib2-2.5.3-a3836654.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.antlr\antlr4-runtime\4.10.1\10839f875928f59c622d675091d51a43ea0dc5f7\antlr4-runtime-4.10.1.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\baksmali\2.5.3-a3836654\c7d30db9ffdccbbb94411d337294af562182ec15\baksmali-2.5.3-a3836654.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\31.1-android\9222c47cc3ae890f07f7c961bbb3cb69050fe4aa\guava-31.1-android.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.32\8d7d908528a3671fef3712998c7e36c44ab8189\snakeyaml-1.32-android.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-text\1.10.0\3363381aef8cef2dbc1023b3e3a9433b08b64e01\commons-text-1.10.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.12.0\c6842c86792ff03b9f1d1fe2aab8dc23aa6c6f0e\commons-lang3-3.12.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\brut.j.dir\2.7.0\7406de678100db23537ab5c01facb19fd0543dff\brut.j.dir-2.7.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\brut.j.util\2.7.0\448781919338f5046792fc5a43f9ef4dd31bc4f8\brut.j.util-2.7.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.11.0\a2503f302b11ebde7ebc3df41daebe0e4eea3689\commons-io-2.11.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.apktool\brut.j.common\2.7.0\885b84699421cc7391d222027516d4c471004e63\brut.j.common-2.7.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\util\2.5.3-a3836654\fe220073ebc936f3f923b4a948a3a33a7230e7c0\util-2.5.3-a3836654.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.antlr\antlr\3.5.2\c4a65c950bfc3e7d04309c515b2177c00baf7764\antlr-3.5.2.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.antlr\antlr-runtime\3.5.2\cd9cd41361c155f3af0f653009dcecb08d8b4afd\antlr-runtime-3.5.2.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.beust\jcommander\1.48\bfcb96281ea3b59d626704f74bc6d625ff51cbce\jcommander-1.48.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.antlr\stringtemplate\3.2.1\59ec8083721eae215c6f3caee944c410d2be34de\stringtemplate-3.2.1.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\app.revanced\dexlib2\2.5.3-a3836654\22d234fc65d605eb32d9e64703af0c3fbef784f4\dexlib2-2.5.3-a3836654.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\3.0.2\25ea2e8b0c338a877313bd4672d3fe056ea78f0d\jsr305-3.0.2.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.google.guava\failureaccess\1.0.1\1dcf1de382a0bf95a3d8b0849546c88bac1292c9\failureaccess-1.0.1.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.google.guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\b421526c5f297295adef1c886e5246c39d4ac629\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.checkerframework\checker-qual\3.12.0\d5692f0526415fcc6de94bb5bfbd3afd9dd3b3e5\checker-qual-3.12.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.google.errorprone\error_prone_annotations\2.11.0\c5a0ace696d3f8b1c1d8cc036d8c03cc0cbe6b69\error_prone_annotations-2.11.0.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\com.google.j2objc\j2objc-annotations\1.3\ba035118bc8bac37d7eff77700720999acd9986d\j2objc-annotations-1.3.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\org.antlr\ST4\4.0.8\a1c55e974f8a94d78e2348fa6ff63f4fa1fae64\ST4-4.0.8.jar;C:\Users\SoporteTI\.gradle\caches\modules-2\files-2.1\antlr\antlr\2.7.7\83cd2cd674a217ade95a4bb83a8a14f351f48bd0\antlr-2.7.7.jar" app.revanced.cli.main.MainKt --options ../options.toml -o ../revanced.apk -a ../binaries/unpatched-input.apk -t ../revanced-cache -b ../revanced-patches/build/libs/revanced-patches-2.169.1-dev.4.jar -m ../revanced-integrations/app/build/outputs/apk/release/revanced-integrations-0.103.1-dev.2.apk -d device-name
java.nio.file.NoSuchFileException: ..\revanced-patches\build\libs\revanced-patches-2.169.1-dev.4.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:284)
	at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:45)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

Process finished with exit code 0
```

### Screenshots or videos

![Config 1](https://user-images.githubusercontent.com/73723969/233859574-d62303fe-38bf-4ff2-bf7e-cfc6eb71d043.png)
![config 2](https://user-images.githubusercontent.com/73723969/233859580-2d7a056b-0785-4118-982a-252bcf3e8d23.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The relative file path for patches does not exist.

**Comment by jhcarlos8888** [comment]
> The relative file path for patches does not exist.

Please the solution for the error is ?
