### ISSUE TITLE
bug; Failing to sign the apk

### ISSUE THREAD

**Issue by adamsatyr** [revanced/revanced-cli#220]
### Type

Error while running the CLI

### Bug description

Revanced CLI fails at signing stage

### Steps to reproduce

Try to use newest file versions and run the command.

Using Java SDK 17

### Relevant log output

```shell
(base) PS Z:\revanced> java -jar re-cli.jar -a yt.apk -c -o ReVanced.apk -b patches.jar -m inte.apk
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
(base) PS Z:\revanced> java -jar re-cli.jar -a yt.apk -c -o ReVanced.apk -b patches.jar -m inte.apk
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping change-package-name: Excluded by default
INFO: Skipping custom-video-buffer: Excluded by default
INFO: Skipping enable-android-debugging: Excluded by default
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Merging inte.apk
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: always-autorepeat succeeded
INFO: client-spoof succeeded
INFO: comments succeeded
INFO: copy-video-url succeeded
INFO: custom-branding succeeded
INFO: custom-video-speed succeeded
INFO: disable-auto-captions succeeded
INFO: disable-fullscreen-panels succeeded
INFO: disable-player-popup-panels succeeded
INFO: disable-shorts-on-startup succeeded
INFO: disable-zoom-haptics succeeded
INFO: downloads succeeded
INFO: enable-debugging succeeded
INFO: general-ads succeeded
INFO: hdr-auto-brightness succeeded
INFO: hide-album-cards succeeded
INFO: hide-artist-card succeeded
INFO: hide-autoplay-button succeeded
INFO: hide-breaking-news-shelf succeeded
INFO: hide-captions-button succeeded
INFO: hide-cast-button succeeded
INFO: hide-create-button succeeded
INFO: hide-crowdfunding-box succeeded
INFO: hide-email-address succeeded
INFO: hide-endscreen-cards succeeded
INFO: hide-floating-microphone-button succeeded
INFO: hide-info-cards succeeded
INFO: hide-player-buttons succeeded
INFO: hide-player-overlay succeeded
INFO: hide-seekbar succeeded
INFO: hide-shorts-button succeeded
INFO: hide-timestamp succeeded
INFO: hide-video-action-buttons succeeded
INFO: hide-watch-in-vr succeeded
INFO: hide-watermark succeeded
INFO: minimized-playback succeeded
INFO: old-quality-layout succeeded
INFO: open-links-externally succeeded
INFO: premium-heading succeeded
INFO: remember-playback-speed succeeded
INFO: remember-video-quality succeeded
INFO: remove-player-button-background succeeded
INFO: return-youtube-dislike succeeded
INFO: seekbar-tapping succeeded
INFO: sponsorblock succeeded
INFO: spoof-app-version succeeded
INFO: spoof-signature-verification succeeded
INFO: swipe-controls succeeded
INFO: tablet-mini-player succeeded
INFO: theme succeeded
INFO: vanced-microg-support succeeded
INFO: video-ads succeeded
INFO: wide-searchbar succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning yt.apk to ReVanced_aligned.apk
INFO: Signing ReVanced_aligned.apk to ReVanced_signed.apk
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
        at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:29)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:58)
        at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more
(base) PS Z:\revanced>
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#115

**Comment by toine512** [comment]
Don't write in the manual it works with OpenJDK then.

**Comment by oSumAtrIX** [comment]
It should work with OpenJDK. Have you tried Azul Zulu? If OpenJDK does not work, please open a PR to remove it.
