### ISSUE TITLE
bug: java.io.FileNotFoundException: input.apk (Permission denied)

### ISSUE THREAD

**Issue by JPZV** [revanced/revanced-cli#231]
### Type

Error while running the CLI

### Bug description

I'm trying to patch Instagram with a new patch that I made, and everything works fine until it has to sign the patched apk, where it stops with the following exception:

```
java.io.FileNotFoundException: instagram.apk (The Process Cannot Access The File Used by Another Process)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at app.revanced.utils.signing.align.zip.ZipFile.<init>(ZipFile.kt:16)
        at app.revanced.cli.aligning.Aligning.align(Aligning.kt:32)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

I tried with both [v2.21.4](https://github.com/revanced/revanced-cli/releases/tag/v2.21.4) and [v2.21.5-dev.1](https://github.com/revanced/revanced-cli/releases/tag/v2.21.5-dev.1). I think the problem becomes because the `inputfile` wasn't closed before aligning it.

### Steps to reproduce

1) Download the latest revanced-cli.jar from releases
2) Download the following [revanced-patches.jar](https://github.com/revanced/revanced-cli/files/11886076/revanced-patches.zip) and Instagram.apk version **288.1.0.22.66** (although I think this should happen on any apk)
3) Use the following command: `java -jar revanced-cli.jar -b revanced-patches-2.178.0.jar -a instagram.apk -o revanced.apk`

### Relevant log output

```shell
INFO: Executing patches
INFO: inst-enable-features succeeded
INFO: Not compiling resources because resource patching is not required
INFO: Writing modified dex files
INFO: Aligning instagram.apk to instagram.patched_aligned.apk
java.io.FileNotFoundException: .\instagram.apk (The Process Cannot Access The File Used by Another Process)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at app.revanced.utils.signing.align.zip.ZipFile.<init>(ZipFile.kt:16)
        at app.revanced.cli.aligning.Aligning.align(Aligning.kt:32)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Additional context

I made a new patch called inst-enable-features which should work on Instagram 288.1.0.22.66, and the patched apk should only contain that patch

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The file is inaccessible by the user you launched ReVanced CLI with

**Comment by JPZV** [comment]
That's not correct. Same thing when running PowerShell as Administrator.

![image](https://github.com/revanced/revanced-cli/assets/38300410/ff05b1d6-10b5-437e-8082-ccb4830fbd90)

**Comment by oSumAtrIX** [comment]
The permission error is propagated from your OS. Your user can not propagate file permission access to eVanced CLI
