### ISSUE TITLE
bug: Where is the help for available options?

### ISSUE THREAD

**Issue by 54m4d** [ReVanced/revanced-cli#248]
### Type

Error while running the CLI

### Bug description

The help for available options have disappeared and i can't get cli to work as in the previous version, something has changed.

The help must be complete to be able to use the cli properly.

### Steps to reproduce

Generate the help

### Relevant log output

```shell
N/A
```

### Screenshots or videos

```
java -jar revanced-cli-3.0.0-all.jar -h

Usage: revanced-cli [-hV] [COMMAND]
Command line application to use ReVanced
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  list-patches  List patches from supplied patch bundles
  patch         Patch the supplied APK file with the supplied patches and
                  integrations
  options       Generate options file from patches
  utility       Commands for utility purposes
```

### Additional context

It used to be like this:

```
Usage: ReVanced-CLI [-hV] (-a=<inputFile> [--uninstall] [-d=<deploy>]
                    [-b=<patchBundles> [-b=<patchBundles>]...
                    [--options=<optionsFile>] [-l [--with-versions]
                    [--with-packages]] [-o=<outputPath>
                    [-e=<excludedPatches>]... [--exclusive]
                    [-i=<includedPatches>]... [--experimental]
                    [-m=<mergeFiles>]... [--mount] [--cn=<cn>]
                    [--keystore=<keystorePath>] [-p=<password>]
                    [-t=<cacheDirectory>] [-c]
                    [--custom-aapt2-binary=<aaptPath>]]])
  -a, --apk=<inputFile>      Input APK file to be patched
  -b, --bundle=<patchBundles>
                             One or more bundles of patches
  -c, --clean                Clean the temporary resource cache directory. This
                               will be done anyways when running the patcher
      --cn=<cn>              Overwrite the default CN for the signed file
      --custom-aapt2-binary=<aaptPath>
                             Path to custom aapt2 binary
  -d, --deploy-on=<deploy>   If specified, deploy to device over ADB with given
                               name
  -e, --exclude=<excludedPatches>
                             Explicitly exclude patches
      --exclusive            Only installs the patches you include, not
                               including any patch by default
      --experimental         Disable patch version compatibility patch
  -h, --help                 Show this help message and exit.
  -i, --include=<includedPatches>
                             Include patches
      --keystore=<keystorePath>
                             File path to your keystore
  -l, --list                 List patches
  -m, --merge=<mergeFiles>   One or more dex file containers to merge
      --mount                If specified, instead of installing, mount
  -o, --out=<outputPath>     Output file path
      --options=<optionsFile>
                             Path to patch options JSON file
  -p, --password=<password>  Overwrite the default password for the signed file
  -t, --temp-dir=<cacheDirectory>
                             Temporary resource cache directory
      --uninstall            Uninstall the mount variant
  -V, --version              Print version information and exit.
      --with-packages        List patches with compatible packages
      --with-versions        List patches with compatible versions
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Type the subcommands for help on the subcommands

**Comment by 54m4d** [comment]
And how do i suppose to know what subcommands are available?

**Comment by oSumAtrIX** [comment]
By looking at what -h prints:

![image](https://github.com/ReVanced/revanced-cli/assets/13122796/589767b4-87db-433e-87fd-2b9a3c946db0)

**Comment by 54m4d** [comment]
What is the commands to list more information about e.g. -a -b -c ?

**Comment by oSumAtrIX** [comment]
It is automatically printed when you type the subcommand

**Comment by 54m4d** [comment]
Can you write an example of what you mean, the old behavour was more simple, but if you give example i'll try to see if i can adapt

**Comment by oSumAtrIX** [comment]
`java -jar revanced-cli*.jar patch`

**Comment by 54m4d** [comment]
Bro, please fix the wording, it's confusing and not easily accessible, i woudn't know that `java -jar revanced-cli*.jar patch` would print what it prints, the help just says that it's a command.

**Comment by oSumAtrIX** [comment]
The wording is correct. If you have an issue, open it in the CLI parser's respective repository.
https://picocli.info/#_executing_commands_with_subcommands

**Comment by 54m4d** [comment]
I mean like make us aware on how to print the help for the options, like a phrase stating how to learn more about the options or something similar.

**Comment by oSumAtrIX** [comment]
You are welcome suggesting the sentence for the docs in a new issue or PR.

**Comment by 54m4d** [comment]
I will try

**Comment by 54m4d** [comment]
I'm just trying to successfully patch an apk for once, but i'm getting the help printed instead.

What's wrong with this one?
```
java -jar revanced-cli-3.0.0-all.jar --patch-bundle revanced-patches-2.188.0.jar --merge revanced-integrations-0.116.0.apk --apk FILE.apk --out revanced.apk
```

**Comment by oSumAtrIX** [comment]
What does the output say

**Comment by 54m4d** [comment]
The help gets printed instead

**Comment by oSumAtrIX** [comment]
You are missing the subcommand, check the docs for usage of the commands.

**Comment by 54m4d** [comment]
The `--apk` option was the one causing the issue since it's removed in this release. it's working now.

**Comment by 54m4d** [comment]
@oSumAtrIX Bro, there are issues with `v2.188.1` not sure if it's only me? `v2.188.0` works fine. Should i create a separate issue?

```
java -jar revanced-cli-3.0.0-all.jar patch -b revanced-patches-2.188.1.jar -m revanced-integrations-0.116.2.apk 18.23.35.apk -o revanced.apk
```
```java
INFO: Loading patches
INFO: Setting patch options
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/PatchResultError
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3397)
        at java.base/java.lang.Class.getDeclaredField(Class.java:2705)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:113)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
        at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:57)
        at app.revanced.patcher.extensions.PatchExtensions.getOptions(PatchExtensions.kt:60)
        at app.revanced.utils.Options.serialize(Options.kt:27)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.PatchResultError
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 21 more
```

**Comment by kazimmt** [comment]
>there are issues with `v2.188.1` not sure if it's only me? `v2.188.0` works fine. Should i create a separate issue?

Use Previous CLI for Now!

**Comment by oSumAtrIX** [comment]
@54m4d No, the patches have been reverted to the previous patcher version for now

**Comment by 54m4d** [comment]
Since i don't have a lower Android version, can this be optional?

**Comment by oSumAtrIX** [comment]
Yes.

**Comment by 54m4d** [comment]
OK, but on Manager, any idea how to downgrade the patches from `v2.188.1` to `v2.188.0`?

**Comment by kazimmt** [comment]
There is no way with current Manager

**Comment by 54m4d** [comment]
OK

**Comment by SodaWithoutSparkles** [comment]
Regarding the orginal issue, i do think the help flag should be present on subcommands.

Either do it like `adb --help` and print all help for subcommands, or;

Do it like `docker --help` and `docker compose --help` and provide detailed help on each subcommand separately. 

You are not suppose to run a command w/o at least reading the help first.

**Comment by oSumAtrIX** [comment]
PicoCLI powers the command framework. You should open an issue in the respective repository.
