### ISSUE TITLE
bug: NoClassDefFoundError

### ISSUE THREAD

**Issue by MarrMann** [ReVanced/revanced-cli#250]
### Type

Error while running the CLI

### Bug description

Exception thrown when trying to build options or when patching, following the instructions.
Tried using JDK 11 and JDK 17.

### Steps to reproduce

Step 1. Download JDK 11 using chocolately: `choco install zulu11`
Step 1. Follow instructions, download cli, patches, integrations, and a YouTube apk.
Step 2. Run the command ` java -jar .\revanced-cli.jar options --path options.json --overwrite .\revanced-patches.jar`
Step 3. The exception from the log/screenshot should be shown.

### Relevant log output

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/PatchResultError
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
        at java.base/java.lang.Class.getDeclaredField(Class.java:2409)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:113)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
        at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:57)
        at app.revanced.patcher.extensions.PatchExtensions.getOptions(PatchExtensions.kt:60)
        at app.revanced.utils.Options.serialize(Options.kt:27)
        at app.revanced.cli.command.OptionsCommand.run(OptionsCommand.kt:43)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.PatchResultError
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 21 more
```

### Screenshots or videos

![billede](https://github.com/ReVanced/revanced-cli/assets/59193792/e8fac2e4-2748-49fa-a5c3-1ad2c570f68a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-cli/issues/249

**Comment by MarrMann** [comment]
I don't understand how those issues are related. Same thing happens when I just run `java -jar .\revanced-cli.jar options .\revanced-patches.jar`

**Comment by oSumAtrIX** [comment]
Check https://github.com/ReVanced/revanced-cli/issues/248#issuecomment-1694644827
