### ISSUE TITLE
bug: Error loading patches

### ISSUE THREAD

**Issue by NoelJacob** [ReVanced/revanced-cli#251]
### Type

Error while running the CLI

### Bug description

`java -jar ./cli/v3.0.0/revanced_cli.jar options ./patches/v2.188.1/revanced_patches.jar`
```
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/PatchResultError
at java.base/java.lang.Class.getDeclaredFields0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
at java.base/java.lang.Class.getDeclaredField(Class.java:2608)
at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:113)
at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:57)
at app.revanced.patcher.extensions.PatchExtensions.getOptions(PatchExtensions.kt:60)
at app.revanced.utils.Options.serialize(Options.kt:27)
at app.revanced.cli.command.OptionsCommand.run(OptionsCommand.kt:43)
at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
at picocli.CommandLine.execute(CommandLine.java:2170)
at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.PatchResultError
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 21 more
```

### Steps to reproduce

Just do as above normally.

### Relevant log output

```shell
Given above.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-cli/issues/250
