### ISSUE TITLE
bug: Error when using Crostini VM to patch yt

### ISSUE THREAD

**Issue by VenomousSteam81** [ReVanced/revanced-cli#260]
### Type

Error while running the CLI

### Bug description

I was trying to patch with CLI (obviously)

### Steps to reproduce

Step 1: do the stuff
Step 2: error

### Relevant log output

```shell
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_12282424379730092243239792739059968688.tmp, compile, --dir, /mnt/chromeos/removable/chromebook/revanced/revanced-resource-cache/res, --legacy, -o, /mnt/chromeos/removable/chromebook/revanced/revanced-resource-cache/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
        at app.revanced.patcher.Patcher.get(Patcher.kt:232)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:195)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_12282424379730092243239792739059968688.tmp, compile, --dir, /mnt/chromeos/removable/chromebook/revanced/revanced-resource-cache/res, --legacy, -o, /mnt/chromeos/removable/chromebook/revanced/revanced-resource-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
```

### Screenshots or videos

None

### Solution

N/A

### Additional context

The device is a Chromebook

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
What architecture is it?
