### ISSUE TITLE
bug: using old keystores no longer works

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-cli#272]
### Type

Error while running the CLI

### Bug description

A recent change has broken compatibility with previously generated keystores.

Deleting the existing keystore and patching works, but that generates a new keystore and it's no possible to upgrade previously patched apps.

### Steps to reproduce

- patch any app using a keystore generated with a previous CLI release
- patching fails with `Keystore does not contain alias ReVanced Key`

### Relevant log output

```shell
INFO: Aligning youtube_18.32.39.apk 
java.lang.IllegalArgumentException: Keystore does not contain alias ReVanced Key
	at app.revanced.library.ApkSigner.readKeyCertificatePair(ApkSigner.kt:91)
	at app.revanced.library.ApkSigner.newApkSignerBuilder(ApkSigner.kt:227)
	at app.revanced.library.ApkUtils.sign(ApkUtils.kt:79)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The compatibility is dropped due to the keystore entry being renamed, so it doesn't find the correct entry anymore. We can add back compatibility for this

**Comment by oSumAtrIX** [comment]
Never mind, backward compatibility is still present. Previously the alias was called "alias":

![image](https://github.com/ReVanced/revanced-cli/assets/13122796/bc77b073-21a3-4adf-b446-d56ec216646a)

Now you can specify it using the option `--alias`.

**Comment by GieltjE** [comment]
```--alias=alias --keystore-entry-password=ReVanced --keystore-password=ReVanced```
That works for old keystores.

Would backwards compatibility mean just detect the alias/password or are we moving to some new randomized password scheme?

**Comment by oSumAtrIX** [comment]
The new default password is "", so basically no password
