### ISSUE TITLE
bug: KeyStore integrity check failed.

### ISSUE THREAD

**Issue by Gontier-Julien** [ReVanced/revanced-cli#277]
### Bug description

I was trying to patch as usual Youtube but since V4 i can't figure out why i can get it working.

I already tried the solutions in #272 but without luck.

The keystore is from ReVanced Manager from July 8 2023 if that can help.

I even tried a new one from ReVanced Manager but without luck either.

I build it in a docker with `azul/zulu-openjdk-alpine:11-latest`

I tried originally with the good password but no luck either there :(

The command:
`--keystore="/build/revanced.keystore" --alias="alias" --keystore-entry-password="ReVanced" --keystore-password="ReVanced"`

### Error logs

```shell
INFO: Aligning com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk 
java.io.IOException: KeyStore integrity check failed.
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at app.revanced.library.ApkSigner.readKeyStore(ApkSigner.kt:165)
	at app.revanced.library.ApkUtils.sign(ApkUtils.kt:66)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You are missing the keystore password which happened to be ReVanced too in v3

**Comment by Gontier-Julien** [comment]
> You are missing the keystore password which happened to be ReVanced too in v3

But it was all working in V3 with just `--keystore=/build/revanced.keystore --keystore-password=_the passorwd that was working with it_`

So what am i missing here ? I'm kinda confused, because in V3 it wasn't "ReVanced"

I'll try again tomorrow but i don't think that it while work :(

**Comment by oSumAtrIX** [comment]
You need the keystore as well as entry password

**Comment by Gontier-Julien** [comment]
> You need the keystore as well as entry password

So I'll just need to add `--keystore-entry-password` and it is the same password then as `--keystore-password` from what I understand?

**Comment by Gontier-Julien** [comment]
I was able to solve it thank for you're help! 👍🏻
