### ISSUE TITLE
bug: I can no longer use my keystone in the revanced cli

### ISSUE THREAD

**Issue by juniosxs** [ReVanced/revanced-cli#285]
### Bug description

everything worked fine, but after some updates I can't generate the mod using my keystore, I'm getting the following error

### Error logs

```shell
java.lang.IllegalArgumentException: Keystore does not contain alias ReVanced Key
        at app.revanced.library.ApkSigner.readKeyCertificatePair(ApkSigner.kt:91)
        at app.revanced.library.ApkSigner.newApkSignerBuilder(ApkSigner.kt:228)
        at app.revanced.library.ApkUtils.sign(ApkUtils.kt:79)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Finished
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You need to specify the correct keystore alias.

**Comment by auanasgheps** [comment]
I have the same issue. How do we specify the keystore alias?

**Comment by juniosxs** [comment]
> Eu tenho o mesmo problema. Como especificamos o alias do keystore?

https://github.com/juniosxs/builder-revanced/blob/d350550596ad8ab65541cb28105e8bf0ff5cb087/build-youtube.sh#L10C1-L10C1

**Comment by juniosxs** [comment]
> I have the same issue. How do we specify the keystore alias?

Now you need to inform the keystore alias as you can see in this screenshot of my script, you need to inform the alias.

![IMG_20231014_094348](https://github.com/ReVanced/revanced-cli/assets/86573479/46be4840-868a-46aa-aa69-c3b0ddb161f6)
