### ISSUE TITLE
bug: Compiling error

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-cli#294]
### Bug description

Error occured while compiling
```
java -jar revanced-cli.jar patch -p -o Install\YouTube_ReVanced.apk -b revanced-patches.jar --keystore=ks.keystore -m revanced-integrations.apk YouTube.apk
```

INFO: Loading patches
INFO: Decoding app manifest
INFO: Custom branding excluded
INFO: Remove player controls background excluded
INFO: Remove screen capture restriction excluded
INFO: Export all activities excluded
INFO: Remove screenshot restriction excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Change package name excluded
INFO: Predictive back gesture excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Alternative thumbnails succeeded
INFO: Always autorepeat succeeded
INFO: Announcements succeeded
INFO: Bypass URL redirects succeeded
INFO: Client spoof succeeded
INFO: Comments succeeded
INFO: Copy video url succeeded
INFO: Custom player overlay opacity succeeded
INFO: Disable Shorts on startup succeeded
INFO: Disable auto captions succeeded
INFO: Disable fine scrubbing gesture succeeded
INFO: Disable player popup panels succeeded
INFO: Disable zoom haptics succeeded
INFO: Enable debugging succeeded
INFO: Enable tablet layout succeeded
INFO: External downloads succeeded
INFO: HDR auto brightness succeeded
INFO: Hide 'Load more' button succeeded
INFO: Hide Shorts components succeeded
INFO: Hide ads succeeded
INFO: Hide album cards succeeded
INFO: Hide autoplay button succeeded
INFO: Hide breaking news shelf succeeded
INFO: Hide captions button succeeded
INFO: Hide cast button succeeded
INFO: Hide crowdfunding box succeeded
INFO: Hide email address succeeded
INFO: Hide endscreen cards succeeded
INFO: Hide filter bar succeeded
INFO: Hide floating microphone button succeeded
INFO: Hide info cards succeeded
INFO: Hide layout components succeeded
INFO: Hide player buttons succeeded
INFO: Hide seekbar succeeded
INFO: Hide timestamp succeeded
INFO: Hide video action buttons succeeded
INFO: Minimized playback succeeded
INFO: Navigation buttons succeeded
INFO: Old video quality menu succeeded
INFO: Open links externally succeeded
INFO: Playback speed succeeded
INFO: Player flyout menu succeeded
INFO: Premium heading succeeded
INFO: Remember video quality succeeded
INFO: Return YouTube Dislike succeeded
INFO: Seekbar tapping succeeded
INFO: SponsorBlock succeeded
INFO: Spoof app version succeeded
INFO: Spoof device dimensions succeeded
INFO: Swipe controls succeeded
INFO: Tablet mini player succeeded
INFO: Theme succeeded
INFO: Vanced MicroG support succeeded
INFO: Video ads succeeded
INFO: Wide searchbar succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_150805408543984987097325703608612933572.tmp, compile, --dir, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\res, --legacy, -o, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\build\resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
        at app.revanced.patcher.Patcher.get(Patcher.kt:262)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:234)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_150805408543984987097325703608612933572.tmp, compile, --dir, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\res, --legacy, -o, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\build\resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more

### Error logs

```shell
INFO: Compiling modified resources
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_150805408543984987097325703608612933572.tmp, compile, --dir, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\res, --legacy, -o, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\build\resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
        at app.revanced.patcher.Patcher.get(Patcher.kt:262)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:234)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_150805408543984987097325703608612933572.tmp, compile, --dir, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\res, --legacy, -o, E:\ANDROID\APPS\ReVanced\Patched\revanced-resource-cache.\build\resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
```

### Additional context

cli [v4.0.3-dev.1](https://github.com/ReVanced/revanced-cli/releases/tag/v4.0.3-dev.1)
inte [v0.120.1-dev.3](https://github.com/ReVanced/revanced-integrations/releases/tag/v0.120.1-dev.3)
patches [v2.196.0-dev.3](https://github.com/ReVanced/revanced-patches/releases/tag/v2.196.0-dev.3)

Tested with pixiv working, but not for youtube

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Have you touched patch options?

**Comment by cyberboh** [comment]
> Have you touched patch options?

You mean `options.json`? If so, i never touch it bcs of i patch all apps with default patches.

**Comment by oSumAtrIX** [comment]
Which architecture do you patch on?

**Comment by cyberboh** [comment]
> Which architecture do you patch on?

Windows 10 x64 with Azul JDK 17

**Comment by oSumAtrIX** [comment]
What if you only include Vanced MicroG patch?

**Comment by cyberboh** [comment]
> What if you only include Vanced MicroG patch?

All good tho

```
java -jar revanced-cli.jar patch -p -o Install\YouTube_ReVanced.apk -b revanced-patches.jar --keystore=ks.keystore -m revanced-integrations.apk YouTube.apk --exclusive -i "Vanced MicroG support"
INFO: Loading patches
INFO: Decoding app manifest
INFO: Enable debugging excluded
INFO: Announcements excluded
INFO: Bypass URL redirects excluded
INFO: Open links externally excluded
INFO: Client spoof excluded
INFO: Disable zoom haptics excluded
INFO: Spoof device dimensions excluded
INFO: Always autorepeat excluded
INFO: Minimized playback excluded
INFO: Remember video quality excluded
INFO: Old video quality menu excluded
INFO: HDR auto brightness excluded
INFO: Playback speed excluded
INFO: Video ads excluded
INFO: Hide ads excluded
INFO: Copy video url excluded
INFO: Swipe controls excluded
INFO: Seekbar tapping excluded
INFO: Disable fine scrubbing gesture excluded
INFO: External downloads excluded
INFO: Enable tablet layout excluded
INFO: Custom branding excluded
INFO: Premium heading excluded
INFO: Hide crowdfunding box excluded
INFO: Hide info cards excluded
INFO: Hide breaking news shelf excluded
INFO: Hide timestamp excluded
INFO: Comments excluded
INFO: Hide seekbar excluded
INFO: Hide Shorts components excluded
INFO: Hide layout components excluded
INFO: Player flyout menu excluded
INFO: Hide 'Load more' button excluded
INFO: Hide floating microphone button excluded
INFO: Hide endscreen cards excluded
INFO: Hide album cards excluded
INFO: Hide filter bar excluded
INFO: Hide email address excluded
INFO: Wide searchbar excluded
INFO: Alternative thumbnails excluded
INFO: Tablet mini player excluded
INFO: Spoof app version excluded
INFO: Disable auto captions excluded
INFO: Disable Shorts on startup excluded
INFO: SponsorBlock excluded
INFO: Custom player overlay opacity excluded
INFO: Remove player controls background excluded
INFO: Theme excluded
INFO: Hide cast button excluded
INFO: Navigation buttons excluded
INFO: Hide player buttons excluded
INFO: Hide captions button excluded
INFO: Hide video action buttons excluded
INFO: Hide autoplay button excluded
INFO: Disable player popup panels excluded
INFO: Return YouTube Dislike excluded
INFO: Remove screen capture restriction excluded
INFO: Export all activities excluded
INFO: Remove screenshot restriction excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Change package name excluded
INFO: Predictive back gesture excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Vanced MicroG support succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
INFO: Aligning YouTube.apk
INFO: Signing YouTube.apk
INFO: Purging temporary files
INFO: Failed to purge resource cache directory
```

Compiled successfully

**Comment by oSumAtrIX** [comment]
Alright, then one of the patches causes the issue. Do a half interval search to pinpoint the patch

**Comment by oSumAtrIX** [comment]
You are using dev patches, move to main branch
