### ISSUE TITLE
bug (CLI v4.4.2): Certificate isn't installed properly in patched apk

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-cli#316]
### Bug description

Patch any revanced app with CLI e.g YT Music:

`java -jar revanced-cli-4.4.2-all.jar patch -p -o Install\YouTube_Music_6.40.52-arm64-v8a_ReVanced.apk --options options.json -b revanced-patches-4.4.0-dev.3.jar --alias={} --keystore-password={} --keystore-entry-password={} --keystore={}.keystore -m revanced-integrations-1.5.0-dev.3.apk Apps\com.google.android.apps.youtube.music-6.40.52-arm64-v8a.apk`

Then install patched apk with `adb`

`adb install YouTube_Music_6.40.52-arm64-v8a_ReVanced.apk`

It will give error message like this:

`adb: failed to install E:\ANDROID\APPS\ReVanced\Patched\Install\YouTube_Music_6.40.52-arm64-v8a_ReVanced.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1298955874.tmp/base.apk: Attempt to get length of null array]`

### Error logs

```shell
IDK how to take a logs from CLI while compiling patched apk
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by allemand-instable** [comment]
I can confirm having the same issue with the following trace :

```
at se.vidstige.jadb.managers.PackageManager.verifyOperation(PackageManager.java:43)
	at se.vidstige.jadb.managers.PackageManager.install(PackageManager.java:61)
	at se.vidstige.jadb.managers.PackageManager.install(PackageManager.java:65)
	at app.revanced.library.adb.AdbManager$UserAdbManager.install(AdbManager.kt:149)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:343)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

let me know if there's any more information needed

**Comment by sharunkumar** [comment]
I am facing the same issue when patching through cli and installing:

```
adb: failed to install .\apk\twitter-patched.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1979948300.tmp/base.apk: Attempt to get length of null array]
```

**Comment by oSumAtrIX** [comment]
Somehow the issue was closed accidentally, reopening
