### ISSUE TITLE
bug: Error initialising store of key store: java.lang.SecurityException

### ISSUE THREAD

**Issue by johnconner122** [revanced/revanced-cli#341]
### Bug description

When patching `Youtube`, `org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC` is thrown:

*Steps to reproduce error:*
`java -jar revanced-cli-4.6.0-all.jar patch -b revanced-patches-4.17.0-dev.5.jar -m revanced-integrations-1.16.0-dev.4.apk -o YouTubeRevanced.apk YouTube.apk`

### Error logs

INFO: Aligning APK
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:56)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:114)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:167)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:321)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The issue stems from shading the BC library into the JAR. The BC library is signed and supported to be verified by Java, shading it breaks the signature.

Perhaps something in this direction would solve the issue: https://github.com/GradleUp/shadow/issues/489
