### ISSUE TITLE
Youtube Music v5.03.50 instantly crashes after patching even all patches are excluded

### ISSUE THREAD

**Issue by supericqicq3** [revanced/revanced-cli#35]
Original Music apk which I try to patch works perfectly fine, but patched (even all patches are excluded) crashes. However, the patched Youtube video apk works well.

Versions of revanced packages I used:
- revanced-cli 1.4.2
- revanced-patches 1.6.3
- revanced-integrations 0.10.0

I submit this issue in revanced-cli repository because don't really know where to place it. Sorry if I made a mistake.

Patching and app logs:
```
[skipped] amoled: Explicitly excluded.
[skipped] minimized-playback: Explicitly excluded.
[skipped] disable-create-button: Explicitly excluded.
[skipped] premium-heading: Explicitly excluded.
[skipped] custom-branding: Explicitly excluded.
[skipped] disable-shorts-button: Explicitly excluded.
[skipped] old-quality-layout: Explicitly excluded.
[skipped] hide-cast-button: Explicitly excluded.
[skipped] microg-support: Explicitly excluded.
[skipped] general-ads: Explicitly excluded.
[skipped] video-ads: Explicitly excluded.
[skipped] seekbar-tapping: Explicitly excluded.
[skipped] upgrade-button-remover: Explicitly excluded.
[skipped] tasteBuilder-remover: Explicitly excluded.
[skipped] background-play: Explicitly excluded.
[skipped] exclusive-audio-playback: Explicitly excluded.
[skipped] codecs-unlock: Explicitly excluded.
[aligning & signing]
[deploying]
06-18 15:58:48.073  7255  7255 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-18 15:58:48.082  7255  7255 I AndroidRuntime: Using default boot image
06-18 15:58:48.082  7255  7255 I AndroidRuntime: Leaving lock profiling enabled
06-18 15:58:48.311  7255  7255 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-18 15:58:48.329  7255  7255 D AndroidRuntime: Shutting down VM
06-18 15:58:48.595  7287  7287 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-18 15:58:48.605  7287  7287 I AndroidRuntime: Using default boot image
06-18 15:58:48.605  7287  7287 I AndroidRuntime: Leaving lock profiling enabled
06-18 15:58:48.821  7287  7287 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-18 15:58:48.836  7287  7287 D AndroidRuntime: Shutting down VM
06-18 15:58:49.623  7328  7328 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-18 15:58:49.630  7328  7328 I AndroidRuntime: Using default boot image
06-18 15:58:49.630  7328  7328 I AndroidRuntime: Leaving lock profiling enabled
06-18 15:58:49.826  7328  7328 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-18 15:58:49.844  7328  7328 D AndroidRuntime: Shutting down VM
06-18 15:58:50.697  7426  7426 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-18 15:58:50.704  7426  7426 I AndroidRuntime: Using default boot image
06-18 15:58:50.704  7426  7426 I AndroidRuntime: Leaving lock profiling enabled
06-18 15:58:50.913  7426  7426 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-18 15:58:50.928  7426  7426 D AndroidRuntime: Shutting down VM
06-18 15:58:51.757  7480  7480 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-18 15:58:51.764  7480  7480 I AndroidRuntime: Using default boot image
06-18 15:58:51.764  7480  7480 I AndroidRuntime: Leaving lock profiling enabled
06-18 15:58:51.788  7235  7235 D AndroidRuntime: Shutting down VM
06-18 15:58:51.789  7235  7235 E AndroidRuntime: FATAL EXCEPTION: main
06-18 15:58:51.789  7235  7235 E AndroidRuntime: Process: com.google.android.apps.youtube.music, PID: 7235
06-18 15:58:51.789  7235  7235 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found: needed by /data/data/com.google.android.apps.youtube.music/app_lib/libelements.so.5.03.50 in namespace classloader-namespace
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:929)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at java.lang.System.load(System.java:1620)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at evz.c(PG:48)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at wln.a(PG:7)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at ftf.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at alko.b(PG:8)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at alko.c(PG:5)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at alko.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at qjq.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at wya.<init>(PG:2)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at wyt.<init>(PG:8)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at wyf.f(PG:4)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at wyf.d(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at wyf.c(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at gpc.p(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at gpc.<init>(PG:2)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fom.m(PG:64)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fom.a(PG:37)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at axzg.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fom.h(PG:72)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fom.a(PG:29)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at axzg.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fnk.c(PG:73)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fnk.a(PG:4)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at axzg.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at gqu.<init>(PG:2)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fke.<init>(PG:2)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fkp.b(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at com.google.android.apps.youtube.music.activities.MusicActivity.g(PG:85)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at fhn.a(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at ya.onCreate(PG:3)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at ct.onCreate(PG:1)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at com.google.android.apps.youtube.music.activities.MusicActivity.onCreate(PG:4)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8057)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8037)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-18 15:58:51.789  7235  7235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-18 15:58:51.978  7480  7480 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-18 15:58:51.990  7480  7480 D AndroidRuntime: Shutting down VM
App closed, continuing.
[done]
```

**Comment by oSumAtrIX** [comment]
YouTube Music will not work without a microg patch which is in the works.

**Comment by airend** [comment]
@oSumAtrIX, this `dlopen` issue happens with the root version as well.

`E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found: needed by /data/data/com.google.android.apps.youtube.music/app_lib/libelements.so.5.03.50 in namespace classloader-namespace`

This seems unrelated to `microG` support, and more like a `gradle` issue?

**Comment by oSumAtrIX** [comment]
As I said, YouTube Music will not work without a microg patch.

**Comment by airend** [comment]
I did build `revanced-patches` with your `microG` PR, which yields the same `dlopen` error.

Thank you for your work. Hopefully, **root** mode YouTube Music will be functional, regardless of `microG` support.

**Comment by Canny1913** [comment]
Because that patch is for Youtube. Not YT music.

**Comment by airend** [comment]
I'm referring to commit e22060b52cf09b5b6fe08d5b9ffb8f102efc6cf5.

**Comment by Sculas** [comment]
> I did build `revanced-patches` with your `microG` PR, which yields the same `dlopen` error.

The MicroG PR is a draft because it's not finished yet, that may also be why it doesn't work for you 🙂

**Comment by airend** [comment]
@supericqicq3, as suspected, that `dlopen` error is unrelated to `microG`. Here's how I managed to fix it manually:

1. Extract `libjsc.so` from the YT Music APK (e.g., `unzip com.google.android.apps.youtube.music.apk lib/arm64-v8a/libjsc.so`)
2. Find where YT Music was mounted (e.g., `path=$( pm path com.google.android.apps.youtube.music | grep base | sed 's/package://g' | sed 's/\/base.apk//g' )`)
3. Copy extracted `libjsc.so` to `$path/lib/arm64`, and adjust permissions (i.e., `-rwxr-xr-x 1 system system 9127104 2022-06-19 11:25 libjsc.so`)

The patched YouTube Music app should start now. Of course, the assumption is that you deployed the app in root mode already.

**Comment by Canny1913** [comment]
YT Music doesn't work at the moment.

**Comment by Canny1913** [comment]
Does the patches work?

**Comment by airend** [comment]
As I said a couple of times already, this is `root` mode deploy (i.e., `-d` and no `--install`). I haven't tested `non-root` mode, but I suspect the `dlopen` error will happen there as well.

The original bug reporter ran into an issue that has nothing to do with the WIP `music-microg-support`. It's an YTM installation issue, possibly from the `patcher`. Alas, the issue was quickly dismissed.

**Comment by Canny1913** [comment]
music-microg-support patch doesn't do anything lol (check the source code). its just a placeholder. non-root music isn't ready yet.

**Comment by Victorbry99** [comment]
I can confirm @airend method fixed my YTM from crashing and yes @Canny1913 all the available music patches work (tough codecs-unlocks patch doesn't unlock Opus on uploaded songs, which only have AAC, but it's probably not the patch's fault, just google not encoding in opus uploaded music I think, because the patch works well with all the other songs)

**Comment by ponces** [comment]
Just to let you know [this](96ec6a0384e4c710c36b99ccf88bb14c5addc7af) commit fixed the need of any lib workaround!
No issues here with root method! Great work @Canny1913 !!

**Comment by oSumAtrIX** [comment]
The link does not point anywhere.

**Comment by ponces** [comment]
> Just to let you know [this](https://github.com/revanced/revanced-cli/commit/96ec6a0384e4c710c36b99ccf88bb14c5addc7af) commit fixed the need of any lib workaround!
> No issues here with root method! Great work @Canny1913 !! 

Fixed!

**Comment by ponces** [comment]
> The link does not point anywhere.

Ups, sorry! It does now 😅

**Comment by TheJeterLP** [comment]
> > The link does not point anywhere.
> 
> Ups, sorry! It does now 😅

So this issue can be closed I guess?

**Comment by ponces** [comment]
I would say yes... Or maybe wait for OP confirmation on this... Idk

**Comment by airend** [comment]
Can confirm that YTM works w/o workarounds now.
