### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by MiLiT3cH** [ReVanced/revanced-cli#351]
### Bug description

failed to signing apk whit revanced-cli

### Error logs

```shell
INFO: Aligning APK
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:52)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:113)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:165)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:336)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more
```

### Additional context

this is the command that i use: java -jar .\revanced-cli-5.0.0-all.jar patch -p .\patches.rvp .\googlefoto.apk

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
On a related note, the reason this error occurs is because bouncycastle is a signed library that is not supposed to be shaded into the final CLI jar. Shading it voids the signature and thus we get java.lang.SecurityException: JCE cannot authenticate the provider BC

**Comment by MiLiT3cH** [comment]
Yeah I tried whit another versione of the but nothing, at the last try i use a portable version of idk and it's work

**Comment by oSumAtrIX** [comment]
Ideally we figure out how to retain the JAR signature of the library from the get go.
