### ISSUE TITLE
ReVanced CLI fails to open patched app

### ISSUE THREAD

**Issue by josesilveiraa** [revanced/revanced-cli#4]
```bash
Exception in thread "main" java.lang.IllegalStateException: ADB returned non-zero status code for command: su -c /data/adb/ReVanced/mount.sh
        at app.revanced.cli.runner.AdbRunnerKt.assertZero(AdbRunner.kt:134)
        at app.revanced.cli.runner.AdbRunnerKt.access$assertZero(AdbRunner.kt:1)
        at app.revanced.cli.runner.AdbRunner$runApk$3.invoke(AdbRunner.kt:68)
        at app.revanced.cli.runner.AdbRunner$runApk$3.invoke(AdbRunner.kt:56)
        at app.revanced.cli.runner.AdbRunnerKt.use(AdbRunner.kt:150)
        at app.revanced.cli.runner.AdbRunnerKt.access$use(AdbRunner.kt:1)
        at app.revanced.cli.runner.AdbRunner.runApk(AdbRunner.kt:56)
        at app.revanced.cli.Main$Companion.runCLI(Main.kt:91)
        at app.revanced.cli.Main$Companion.main(Main.kt:167)
        at app.revanced.cli.Main.main(Main.kt)```

**Comment by oSumAtrIX** [comment]
1. [Check this](https://links.osumatrix.me/ask_en)
2. https://github.com/ReVancedTeam/revanced-cli/blob/58213781e13993cb62942452add2fd6451f16bc6/src/main/kotlin/app/revanced/cli/runner/AdbRunner.kt#L68

Run the script manually and figure out what is causing the issue

**Comment by CriticalRange** [comment]
Btw, i was able to fix this by installing the stock apk that is used while patching with ReVanced, and it fixed.

**Comment by oSumAtrIX** [comment]
Pull the latest changes and try again. Use the `main` branch
