### ISSUE TITLE
brut.androlib.AndrolibException: brut.directory.PathAlreadyExists: res

### ISSUE THREAD

**Issue by MopigamesYT** [revanced/revanced-cli#43]
Hello, when i want to use the cli to install Revanced with this command: 

`java -jar vcli.jar -a youtube.apk -c -d [my device] -o revanced.apk -b revanced-patches-1.8.2.jar -i microg-support -i hide-cast-button -i amoled -i minimized-playback -i premium-heading -i custom-branding -i general-ads -i video-ads -i seekbar-tapping -i upgrade-button-remover -i background-play -i codecs-unlock -i integrations --install`

i receive this error:
brut.androlib.AndrolibException: brut.directory.PathAlreadyExists: res
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:240)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
        at app.revanced.patcher.Patcher.<init>(Patcher.kt:62)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:97)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.directory.PathAlreadyExists: res
        at brut.directory.AbstractDirectory.createDir(AbstractDirectory.java:147)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:229)
        ... 12 more

Any idea on how to fix it? i don't really understand the error...

**Comment by TheJeterLP** [comment]
Wrong usage. See docs for help.
