### ISSUE TITLE
The Apk Signer in the cli is broken - Error initialising store of key store

### ISSUE THREAD

**Issue by akshay-sha** [revanced/revanced-cli#53]
### OUTPUT :

```
java -jar revanced-cli-1.7.0-all.jar -a YouTube_v17.23.35_Original.apk -c -d emulator-5554 -o revanced_yt.apk -b revanced-patches-1.9.1.jar


[added] amoled
[added] minimized-playback
[added] disable-create-button
[added] premium-heading
[added] custom-branding
[added] disable-shorts-button
[added] disable-fullscreen-panels
[added] old-quality-layout
[added] hide-cast-button
[added] microg-support
[added] general-ads
[added] video-ads
[added] seekbar-tapping
[skipped] upgrade-button-remover: Incompatible package.
[skipped] tasteBuilder-remover: Incompatible package.
[skipped] background-play: Incompatible package.
[skipped] exclusive-audio-playback: Incompatible package.
[skipped] codecs-unlock: Incompatible package.
[success] amoled
[success] minimized-playback
[error] disable-create-button:
app.revanced.patcher.patch.implementation.misc.PatchResultError: disable-create-button depends on integrations but the following error was raised: Integrations have not been merged yet. This patch can not succeed without the integrations.
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:242)
	at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282)
	at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:58)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:106)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
[success] premium-heading
[success] custom-branding
[success] disable-shorts-button
[success] disable-fullscreen-panels
[success] old-quality-layout
[success] hide-cast-button
[success] microg-support
[success] general-ads
[success] video-ads
[success] seekbar-tapping
[aligning & signing]
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
	at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:27)
	at app.revanced.utils.signing.Signer.signApk(Signer.kt:56)
	at app.revanced.cli.signing.Signing.start(Signing.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:111)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
	... 15 more```

**Comment by Hafiz-SE** [comment]
facing the same issue here

**Comment by akshay-sha** [comment]
### Workaround for now

> **Use Uber Apk Signer - [**](https://github.com/patrickfav/uber-apk-signer) to sign the generated apk.

### Guide
- Create your own release key using keytool 
`keytool -genkey -v -keystore my-release-key.keystore -alias aliasname -keyalg RSA -keysize 2048 -validity 10000`

- Sign the generated APK with Uber Apk Signer 
`java -jar uber-apk-signer-1.2.1.jar -a revanced_yt.apk --ks my-release-key.keystore --ksAlias aliasname`

**Comment by Hafiz-SE** [comment]
> ### Workaround for now
> > **Use Uber Apk Signer - [Github Repo Link](https://github.com/patrickfav/uber-apk-signer) to sign the generated apk.
> 
> ### Guide
> * Generate the revanced Apk using revanced-cli
>   `java -jar revanced-cli-1.7.0-all.jar -a YouTube_v17.23.35_Original.apk -c -d emulator-5554 -o revanced_yt.apk -b revanced-patches-1.9.1.jar -m integration.apk`
> * Create your own release key using keytool
>   `keytool -genkey -v -keystore my-release-key.keystore -alias aliasname -keyalg RSA -keysize 2048 -validity 10000`
> * Sign the generated APK with the above create release-key using Uber Apk Signer
>   `java -jar uber-apk-signer-1.2.1.jar -a revanced_yt.apk --ks my-release-key.keystore --ksAlias aliasname`

file not found integration.apk

**Comment by akshay-sha** [comment]
> 

Download [This]([ReVanced Integrations](https://github.com/revanced/revanced-integrations/releases/latest)) and put in the same folder.

**Comment by akshay-sha** [comment]
> > 
> 
> Download ([ReVanced Integrations](https://github.com/revanced/revanced-integrations/releases/latest)) and put in the same folder.

Also rename as you require.

**Comment by Hafiz-SE** [comment]
Worked! Thanks

**Comment by TheJeterLP** [comment]
You have to use Zulu JDK as said in instructions. This error happens when you're not using it.

**Comment by DaTigerYT** [comment]
> ### Workaround for now
> ...

Aligned and signed, but "App not installed as parcel conflicts with an existing package". Also, it attempts to update the app rather than create a new one, I thought non-root devices were supposed to create a new application instead?

**Comment by TheJeterLP** [comment]
> > ### Workaround for now
> > ...
> 
> Aligned and signed, but "App not installed as parcel conflicts with an existing package". Also, it attempts to update the app rather than create a new one, I thought non-root devices were supposed to create a new application instead?
> 
> 

They are, do you have a previous version of revanced installed?

**Comment by DaTigerYT** [comment]
> > > ### Workaround for now
> > > ...
> > 
> > 
> > Aligned and signed, but "App not installed as parcel conflicts with an existing package". Also, it attempts to update the app rather than create a new one, I thought non-root devices were supposed to create a new application instead?
> 
> They are, do you have a previous version of revanced installed?

Not of ReVanced but of YouTube (of course, pre-installed / can't uninstall). I do also have regular YouTube Vanced installed.

**Comment by DaTigerYT** [comment]
> You have to use Zulu JDK as said in instructions. This error happens when you're not using it.

Tried again with Zulu installed and received same error.

![image](https://user-images.githubusercontent.com/35151380/174971147-ad7dbd93-cb4e-4650-b059-e957bc644498.png)
![image](https://user-images.githubusercontent.com/35151380/174971237-cddaee45-aa75-4a5b-bd6b-36f6ef98b89a.png)

I didn't restart the device or even close & re-open cmd prompt (I didn't have to for the apk signer or even when I installed ADB SDK), so those could be reasons why there were no change... (I would try again with those changes but I'm an hour late for work)

**Comment by TheJeterLP** [comment]
You have to reopen command prompt yes.

Mit freundlichen Grüßen
Joey Peter

DaTigerYT ***@***.***> schrieb am Mi., 22. Juni 2022, 09:38:

**Comment by oSumAtrIX** [comment]
This is the wrong place for support
