### ISSUE TITLE
Error when installing using the ReVanced CLI (Non-Root)

### ISSUE THREAD

**Issue by Kovinda** [revanced/revanced-cli#68]
java version:
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Zulu18.30+11-CA (build 18.0.1+10)
OpenJDK 64-Bit Server VM Zulu18.30+11-CA (build 18.0.1+10, mixed mode, sharing)

The code i ran:
`java -jar revanced-cli-2.0.0-all.jar -a "com.google.android.youtube_17.24.35-1529994688_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk" -c -d R5CR93118YF -o revanced.apk -b revanced-patches-2.0.1.jar -e disable-shorts-button -m app-release-unsigned.apk`

Output:
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
INFO: Skipping disable-shorts-button: Explicitly excluded
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: seekbar-tapping succeeded
**_Exception in thread_** "main" java.lang.NoSuchMethodError: 'app.revanced.patcher.data.impl.ResourceData$XmlFileHolder app.revanced.patcher.data.impl.ResourceData.getXmlEditor()'
        at app.revanced.patches.youtube.misc.mapping.patch.ResourceIdMappingProviderResourcePatch.execute(ResourceIdMappingProviderResourcePatch.kt:23)
        at app.revanced.patches.youtube.misc.mapping.patch.ResourceIdMappingProviderResourcePatch.execute(ResourceIdMappingProviderResourcePatch.kt:13)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:291)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:307)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:94)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:122)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

**Comment by Canny1913** [comment]
Try downgrading your java version to 17.

**Comment by Kovinda** [comment]
> Try downgrading your java version to 17.

I tried first using 17.0.3 (Azul Zulu: 17.34.19), got the same output. Then I tried using 18.

**Comment by Itroublve** [comment]
Pretty sure this was fixed with the current release.
