### ISSUE TITLE
INFO: Found existing keystore: my-release-key java.io.IOException: Wrong version of key store.

### ISSUE THREAD

**Issue by Phongvngg1** [revanced/revanced-cli#69]
This is log: C:\Users\admin\Downloads\revanced>java -jar revanced-cli-2.0.1-all.jar -a com.google.android.youtube.apk -c  -o revanced.apk -b revanced-patches-2.0.1.jar -m app-release-unsigned.apk --keystore=my-release-key.keystore --experimental
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: seekbar-tapping succeeded
INFO: general-ads succeeded
INFO: video-ads succeeded
INFO: custom-branding succeeded
INFO: premium-heading succeeded
INFO: minimized-playback succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
INFO: disable-create-button succeeded
INFO: amoled succeeded
INFO: disable-shorts-button succeeded
INFO: hide-cast-button succeeded
INFO: microg-support succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes8.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes6.dex
INFO: Writing resources
INFO: Aligning revanced_raw.apk
INFO: Signing revanced_aligned.apk
INFO: Found existing keystore: my-release-key
java.io.IOException: Wrong version of key store.
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(KeyStore.java:1473)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:63)
        at app.revanced.cli.signing.Signing.start(Signing.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:125)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
 
Command to create keystore file: keytool -genkey -v -keystore my-release-key.keystore -alias Android -keyalg RSA -keysize 2048 -validity 10000

**Comment by oSumAtrIX** [comment]
Which java version are you running
