### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ixiDev** [revanced/revanced-cli#81]
Hi there.
Thanks for this project :dagger: 

I try to install it and I get this error 

```

WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music 
Exception in thread "main" java.lang.NoSuchMethodError: 'java.nio.file.FileSystem java.nio.file.FileSystems.newFileSystem(java.nio.file.Path, java.util.Map)'
        at app.revanced.utils.filesystem.ZipFileSystemUtils.<init>(ZipFileSystemUtils.kt:13)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:133)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Decoding resources 
INFO: Reading dex files 
INFO: Merging app-release-unsigned.apk 
INFO: Skipping premium-heading: Explicitly excluded 
INFO: Skipping disable-fullscreen-panels: Explicitly excluded 
INFO: Skipping amoled: Explicitly excluded 
INFO: Skipping hide-cast-button: Explicitly excluded 
INFO: Skipping microg-support: Explicitly excluded 
INFO: Skipping enable-debugging: Explicitly excluded 
INFO: seekbar-tapping succeeded 
INFO: general-ads succeeded 
INFO: video-ads succeeded 
INFO: hide-infocard-suggestions succeeded 
INFO: custom-branding succeeded 
INFO: minimized-playback succeeded 
INFO: old-quality-layout succeeded 
INFO: hide-autoplay-button succeeded 
INFO: disable-create-button succeeded 
INFO: hide-shorts-button succeeded 
INFO: hide-watermark succeeded 
INFO: custom-playback-speed succeeded 
INFO: hdr-max-brightness succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files
``` 

my command is 

`java -jar revanced-cli-all.jar --experimental -a yt.apk -d f8ea68e7 -c -o revanced.apk -b revanced-patches.jar -m app-release-unsigned.apk -e amoled -e premium-heading -e disable-shorts-button -e disable-fullscreen-panels -e hide-cast-button -e microg-support --mount `

I have already  Youtube  v17.24.34 installed, My phone is Xiaomi Redmi Note 8

Thanks

**Comment by oSumAtrIX** [comment]
Wrong java version. You need Zulu 17 as written in the docs.

**Comment by ixiDev** [comment]
Thanks @oSumAtrIX  it's working :D
