### ISSUE TITLE
Does not build an apk [brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):]

### ISSUE THREAD

**Issue by dontdeadopeninside** [revanced/revanced-cli#83]
C:\Users\user\Downloads\revanced>"C:\Program Files\Zulu\zulu-17\bin\java.exe" -jar revanced-cli-2.3.1-all.jar -a youtube.apk -o revanced.apk -b revanced-patches-2.8.0.jar -m app-release-unsigned.apk
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:6: error: resource android:color/background_cache_hint_selector_material_light is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:7: error: resource android:color/background_floating_material_dark is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:8: error: resource android:color/Blue_700 is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:9: error: resource android:color/Indigo_800 is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:10: error: resource android:color/GM2_grey_800 is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:11: error: resource android:color/Red_700 is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:12: error: resource android:color/Teal_700 is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:13: error: resource android:color/accent_device_default_dark_60_percent_opacity is private.
WARNING: C:\Users\user\Downloads\revanced\revanced-cache\res\values-v31\colors.xml:14: error: resource android:color/autofill_background_material_dark is private.
WARNING: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_21614907946224508614034811161087778448.tmp, link, -o, C:\Users\user\Downloads\revanced\revanced-cache\aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530123712, --version-name, 17.25.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\user\AppData\Local\Temp\APKTOOL2182423897097567369.tmp, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\user\Downloads\revanced\revanced-cache\AndroidManifest.xml, C:\Users\user\Downloads\revanced\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:199)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:133)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_21614907946224508614034811161087778448.tmp, link, -o, C:\Users\user\Downloads\revanced\revanced-cache\aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530123712, --version-name, 17.25.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\user\AppData\Local\Temp\APKTOOL2182423897097567369.tmp, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, --manifest, C:\Users\user\Downloads\revanced\revanced-cache\AndroidManifest.xml, C:\Users\user\Downloads\revanced\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
INFO: Skipping enable-debugging: Explicitly excluded
INFO: seekbar-tapping succeeded
INFO: general-ads succeeded
INFO: video-ads succeeded
INFO: hide-infocard-suggestions succeeded
INFO: custom-branding succeeded
INFO: premium-heading succeeded
INFO: minimized-playback succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
INFO: hide-autoplay-button succeeded
INFO: disable-create-button succeeded
INFO: amoled succeeded
INFO: hide-shorts-button succeeded
INFO: hide-cast-button succeeded
INFO: hide-watermark succeeded
INFO: microg-support succeeded
INFO: custom-playback-speed succeeded
INFO: hdr-max-brightness succeeded
INFO: Compiling resources

There is no resulting apk file after this. Only files in cache which contain a revanced_raw.apk whose SHA matches the vanilla youtube apk

**Comment by reisxd** [comment]
Delete %localappdata%/ApkTool
