### ISSUE TITLE
problem: Stopped logging because the app was closed

### ISSUE THREAD

**Issue by kamilmirza** [revanced/revanced-cli#96]
## 🐞 Issue

revanced app does not get installed 
tried the root method described in [HERE](https://github.com/revanced/revanced-documentation/wiki/Using-the-ReVanced-CLI-and-installing-ReVanced)

have executed the following:
`java -jar revanced-cli-2.5.3-all.jar -a YouTube-17.26.35.apk -c -d 192.168.0.111:5555 -o revan
ced.apk -b revanced-patches-2.13.4.jar -e microg-support --mount`

here's the complete log:
```
java -jar revanced-cli-2.5.3-all.jar -a YouTube-17.26.35.apk -c -d 192.168.0.111:5555 -o revan
ced.apk -b revanced-patches-2.13.4.jar -e microg-support --mount
INFO: Decoding resources
INFO: Reading dex files
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping microg-support: Explicitely excluded
INFO: Skipping hdr-auto-brightness: Not explicitly included
INFO: Skipping autorepeat-by-default: Not explicitly included
INFO: Skipping enable-debugging: Not explicitly included
WARNING: Skipping old-quality-layout: Incompatible with version 17.26.35. This patch is only compatible with version com.google.android.youtube: 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35
INFO: Skipping enable-wide-searchbar: Not explicitly included
SEVERE: hide-infocard-suggestions failed:
app.revanced.patcher.patch.PatchResultError: 'hide-infocard-suggestions' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: video-ads failed:
app.revanced.patcher.patch.PatchResultError: 'video-ads' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: general-ads failed:
app.revanced.patcher.patch.PatchResultError: 'general-ads' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: seekbar-tapping failed:
app.revanced.patcher.patch.PatchResultError: 'seekbar-tapping' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: swipe-controls failed:
app.revanced.patcher.patch.PatchResultError: 'swipe-controls' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: custom-playback-speed failed:
app.revanced.patcher.patch.PatchResultError: 'custom-playback-speed' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: hide-cast-button failed:
app.revanced.patcher.patch.PatchResultError: 'hide-cast-button' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: amoled succeeded
INFO: hide-autoplay-button succeeded
INFO: minimized-playback succeeded
INFO: premium-heading succeeded
INFO: custom-branding succeeded
INFO: disable-fullscreen-panels succeeded
SEVERE: hide-shorts-button failed:
app.revanced.patcher.patch.PatchResultError: 'hide-shorts-button' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: disable-create-button failed:
app.revanced.patcher.patch.PatchResultError: 'disable-create-button' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: hide-watermark failed:
app.revanced.patcher.patch.PatchResultError: 'hide-watermark' depends on 'integrations' but the following error was raised: null
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:272)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes8.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes6.dex
INFO: Writing resources...
INFO: Installing by mounting
07-14 00:56:02.695 19812 19812 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-14 00:56:02.710 19812 19812 I AndroidRuntime: Using default boot image
07-14 00:56:02.710 19812 19812 I AndroidRuntime: Leaving lock profiling enabled
07-14 00:56:02.856 19812 19812 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-14 00:56:02.884 19812 19812 D AndroidRuntime: Shutting down VM
INFO: Stopped logging because the app was closed
```

## ⚙ Reproduce
can be reproduced by removing all patches as:
`java -jar revanced-cli-2.5.3-all.jar -a YouTube-17.26.35.apk -c -d 192.168.0.111:5555 -o revanced.apk -b revanced-patches-2.13.4.jar -e microg-support -e hide-infocard-suggestions -e video-ads -e seekbar-tapping -e swipe-controls -e custom-playback-speed -e hide-cast-button -e hide-shorts-button -e disable-create-button -e hide-wate
rmark -e general-ads --mount`
here's the log:
```
java -jar revanced-cli-2.5.3-all.jar -a YouTube-17.26.35.apk -c -d 192.168.0.111:5555 -o revanced.apk -b revanced-patches-2.13.4.jar -e microg-support -e hide-infocard-suggestions -e video-ads -e seekbar-tapping -e swipe-controls -e custom-playback-speed -e hide-cast-button -e hide-shorts-button -e disable-create-button -e hide-wate
rmark -e general-ads --mount
INFO: Decoding resources
INFO: Reading dex files
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping hide-infocard-suggestions: Explicitely excluded
INFO: Skipping video-ads: Explicitely excluded
INFO: Skipping general-ads: Explicitely excluded
INFO: Skipping seekbar-tapping: Explicitely excluded
INFO: Skipping swipe-controls: Explicitely excluded
INFO: Skipping microg-support: Explicitely excluded
INFO: Skipping hdr-auto-brightness: Not explicitly included
INFO: Skipping autorepeat-by-default: Not explicitly included
INFO: Skipping custom-playback-speed: Explicitely excluded
INFO: Skipping enable-debugging: Not explicitly included
WARNING: Skipping old-quality-layout: Incompatible with version 17.26.35. This patch is only compatible with version com.google.android.youtube: 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35
INFO: Skipping hide-cast-button: Explicitely excluded
INFO: Skipping enable-wide-searchbar: Not explicitly included
INFO: Skipping hide-shorts-button: Explicitely excluded
INFO: Skipping disable-create-button: Explicitely excluded
INFO: Skipping hide-watermark: Explicitely excluded
INFO: amoled succeeded
INFO: hide-autoplay-button succeeded
INFO: minimized-playback succeeded
INFO: premium-heading succeeded
INFO: custom-branding succeeded
INFO: disable-fullscreen-panels succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes8.dex
INFO: Writing resources...
INFO: Installing by mounting
07-14 01:12:33.895 21032 21032 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-14 01:12:33.900 21032 21032 I AndroidRuntime: Using default boot image
07-14 01:12:33.900 21032 21032 I AndroidRuntime: Leaving lock profiling enabled
07-14 01:12:34.056 21032 21032 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-14 01:12:34.073 21032 21032 D AndroidRuntime: Shutting down VM
INFO: Stopped logging because the app was closed
```

**Comment by oSumAtrIX** [comment]
![image](https://user-images.githubusercontent.com/13122796/178826856-58ecce08-ab7c-4dc6-90db-f8c9e71476db.png)
Forgot to merge integrations.

**Comment by kamilmirza** [comment]
still the same with integrations
```
java -jar revanced-cli-2.5.3-all.jar -a YouTube-17.26.35.apk -c -d 192.168.70.175:5555 -o reva
nced.apk -b revanced-patches-2.13.4.jar -m app-release-unsigned.apk -e microg-support --mount
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping microg-support: Explicitely excluded
INFO: Skipping hdr-auto-brightness: Not explicitly included
INFO: Skipping autorepeat-by-default: Not explicitly included
INFO: Skipping enable-debugging: Not explicitly included
WARNING: Skipping old-quality-layout: Incompatible with version 17.26.35. This patch is only compatible with version com.google.android.youtube: 17.17.34, 17.19.36, 17.20.37, 17.22.36, 17.23.35, 17.23.36, 17.24.34, 17.24.35
INFO: Skipping enable-wide-searchbar: Not explicitly included
INFO: hide-infocard-suggestions succeeded
INFO: video-ads succeeded
INFO: general-ads succeeded
INFO: seekbar-tapping succeeded
INFO: swipe-controls succeeded
INFO: custom-playback-speed succeeded
INFO: hide-cast-button succeeded
INFO: amoled succeeded
INFO: hide-autoplay-button succeeded
INFO: minimized-playback succeeded
INFO: premium-heading succeeded
INFO: custom-branding succeeded
INFO: disable-fullscreen-panels succeeded
INFO: hide-shorts-button succeeded
INFO: disable-create-button succeeded
INFO: hide-watermark succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes8.dex
INFO: Writing resources...
INFO: Installing by mounting
07-14 09:22:41.630  2795  2795 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-14 09:22:41.635  2795  2795 I AndroidRuntime: Using default boot image
07-14 09:22:41.635  2795  2795 I AndroidRuntime: Leaving lock profiling enabled
07-14 09:22:41.788  2795  2795 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-14 09:22:41.808  2795  2795 D AndroidRuntime: Shutting down VM
INFO: Stopped logging because the app was closed
```

**Comment by TheJeterLP** [comment]
That is a problem from your device

**Comment by kamilmirza** [comment]
output changes by connecting via USB cable
```
07-14 12:00:46.332 15271 15271 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-14 12:00:46.336 15271 15271 I AndroidRuntime: Using default boot image
07-14 12:00:46.336 15271 15271 I AndroidRuntime: Leaving lock profiling enabled
07-14 12:00:46.468 15271 15271 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-14 12:00:46.488 15271 15271 D AndroidRuntime: Shutting down VM
07-14 12:00:46.713  3498  3498 D AndroidRuntime: Shutting down VM
07-14 12:00:46.713  3498  3498 E AndroidRuntime: FATAL EXCEPTION: main
07-14 12:00:46.713  3498  3498 E AndroidRuntime: Process: com.google.android.youtube, PID: 3498
07-14 12:00:46.713  3498  3498 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.google.android.apps.youtube.app.YouTubeTikTokRoot_Application package com.google.android.youtube: java.lang.RuntimeException: Failed to parse XML configuration from locales_config
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1365)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7866)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)07-14 12:00:46.713  3498  3498 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to parse XML configuration from locales_config
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:89)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.getPerDomainConfigs(XmlConfigSource.java:55)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.ManifestConfigSource.getPerDomainConfigs(ManifestConfigSource.java:45)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.ApplicationConfig.ensureInitialized(ApplicationConfig.java:175)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.ApplicationConfig.isCleartextTrafficPermitted(ApplicationConfig.java:130)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.NetworkSecurityConfigProvider.handleNewApplication(NetworkSecurityConfigProvider.java:60)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        ... 10 more
07-14 12:00:46.713  3498  3498 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected start tag: found locale-config, expected network-security-config
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at com.android.internal.util.XmlUtils.beginDocument(XmlUtils.java:1699)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.parseNetworkSecurityConfig(XmlConfigSource.java:315)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:83)
07-14 12:00:46.713  3498  3498 E AndroidRuntime:        ... 16 more
INFO: Stopped logging because the app was closed
```

**Comment by oSumAtrIX** [comment]
Do you have the same version installed on your device for the mount variant?
