### ISSUE TITLE
problem: some problem

### ISSUE THREAD

**Issue by mesofranico** [revanced/revanced-cli#97]
## 🐞 Issue

 org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1195)
        at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:29)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:58)
        at app.revanced.cli.signing.Signing.start(Signing.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)

## ⚙ Reproduce
 java -jar revanced-cli-2.5.3-all.jar -a youtube_17.26.35.apk -c -o revanced.apk -b revanced-patches-2.15.0.jar -m app-release-unsigned25.apk

**Comment by Canny1913** [comment]
Use Zulu JDK 17.
