### ISSUE TITLE
Failed to build an app

### ISSUE THREAD

**Issue by arfaWong** [revanced/revanced-cli#99]
```
root@racknerd-6ae145:~/test# java -jar revanced-cli-2.5.3-all.jar -a youtube-17.27.39.apk -o revanced.apk -b revanced-patches-2.17.0.jar -m app-release-unsigned.apk
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
WARNING: Skipping music-video-ads: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tasteBuilder-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping hdr-auto-brightness: Not explicitly included
INFO: Skipping autorepeat-by-default: Not explicitly included
INFO: Skipping enable-debugging: Not explicitly included
INFO: Skipping force-vp9-codec: Not explicitly included
INFO: Skipping enable-wide-searchbar: Not explicitly included
INFO: hide-infocard-suggestions succeeded
INFO: video-ads succeeded
INFO: general-ads succeeded
INFO: seekbar-tapping succeeded
INFO: swipe-controls succeeded
INFO: microg-support succeeded
INFO: custom-playback-speed succeeded
INFO: sponsorblock succeeded
INFO: old-quality-layout succeeded
INFO: return-youtube-dislike succeeded
INFO: hide-cast-button succeeded
INFO: amoled succeeded
INFO: hide-autoplay-button succeeded
INFO: minimized-playback succeeded
SEVERE: premium-heading failed:
app.revanced.patcher.patch.PatchResultError: The file revanced-cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
        at app.revanced.patches.youtube.layout.branding.header.patch.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:40)
        at app.revanced.patches.youtube.layout.branding.header.patch.PremiumHeadingPatch.execute(PremiumHeadingPatch.kt:19)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:295)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:91)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: custom-branding succeeded
INFO: disable-fullscreen-panels succeeded
INFO: hide-shorts-button succeeded
INFO: disable-create-button succeeded
INFO: hide-watermark succeeded
INFO: Compiling resources
WARNING: /root/test/revanced-cache/res/layout/skip_sponsor_button.xml:5: error: resource drawable/quantum_ic_skip_next_white_24 (aka app.revanced.android.youtube:drawable/quantum_ic_skip_next_white_24) not found.
WARNING: error: failed linking file resources.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_49207638660577060051324198218867063189.tmp, link, -o, /root/test/revanced-cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530396096, --version-name, 17.27.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL2743030664568826768.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, --manifest, /root/test/revanced-cache/AndroidManifest.xml, /root/test/revanced-cache/build/resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:199)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_49207638660577060051324198218867063189.tmp, link, -o, /root/test/revanced-cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 31, --version-code, 1530396096, --version-name, 17.27.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL2743030664568826768.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, --manifest, /root/test/revanced-cache/AndroidManifest.xml, /root/test/revanced-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more
root@racknerd-6ae145:~/test#
```

**Comment by oSumAtrIX** [comment]
Use the proper issue template

**Comment by j4k0xb** [comment]
Had the same issue before. You have to use full instead of base/split apks for root now
